// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rental.DataAccess.Context;

namespace Rental.DataAccess.Migrations
{
    [DbContext(typeof(RentalContext))]
    [Migration("20190807075014_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("r")
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6");

            modelBuilder.Entity("Rental.Core.Entities.BoardGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 8, 7, 7, 50, 13, 757, DateTimeKind.Utc).AddTicks(7655));

                    b.Property<string>("Name");

                    b.Property<float>("PricePerDay");

                    b.Property<float>("SuggestedDeposit");

                    b.HasKey("Id");

                    b.ToTable("BoardGames");
                });

            modelBuilder.Entity("Rental.Core.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactNumber");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 8, 7, 7, 50, 13, 761, DateTimeKind.Utc).AddTicks(9923));

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "1-872-404-5102 x150",
                            CreationTime = new DateTime(2019, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "frank@oreilly.com",
                            FirstName = "Loma",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "025-623-2334 x72540",
                            CreationTime = new DateTime(2019, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lorenza@haleydonnelly.name",
                            FirstName = "Kattie",
                            LastName = "Heller"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "(425)727-8850",
                            CreationTime = new DateTime(2019, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "damon@rowehayes.info",
                            FirstName = "Modesta",
                            LastName = "Price"
                        },
                        new
                        {
                            Id = 4,
                            ContactNumber = "1-127-645-7162 x1724",
                            CreationTime = new DateTime(2019, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "cleveland@prosacco.ca",
                            FirstName = "Nikita",
                            LastName = "Trantow"
                        },
                        new
                        {
                            Id = 5,
                            ContactNumber = "1-427-070-4300 x5865",
                            CreationTime = new DateTime(2019, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "dario@raynoremard.biz",
                            FirstName = "Kane",
                            LastName = "Stark"
                        },
                        new
                        {
                            Id = 6,
                            ContactNumber = "1-605-312-6154 x11277",
                            CreationTime = new DateTime(2019, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "minerva@ratke.name",
                            FirstName = "Isac",
                            LastName = "Fay"
                        },
                        new
                        {
                            Id = 7,
                            ContactNumber = "526-721-2221 x026",
                            CreationTime = new DateTime(2019, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "carissa@shanahan.ca",
                            FirstName = "Gladys",
                            LastName = "Langosh"
                        },
                        new
                        {
                            Id = 8,
                            ContactNumber = "(444)486-4565 x08500",
                            CreationTime = new DateTime(2019, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "don@stoltenberg.name",
                            FirstName = "Kelsie",
                            LastName = "Hills"
                        },
                        new
                        {
                            Id = 9,
                            ContactNumber = "035.340.7806 x71371",
                            CreationTime = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rodolfo_jenkins@gerholdritchie.info",
                            FirstName = "Luz",
                            LastName = "Skiles"
                        },
                        new
                        {
                            Id = 10,
                            ContactNumber = "(616)477-6445 x101",
                            CreationTime = new DateTime(2019, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "nya.towne@gaylord.uk",
                            FirstName = "Bernadine",
                            LastName = "Hahn"
                        },
                        new
                        {
                            Id = 11,
                            ContactNumber = "324-625-4082",
                            CreationTime = new DateTime(2019, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "delphine_schneider@kozey.ca",
                            FirstName = "Carmella",
                            LastName = "Harvey"
                        },
                        new
                        {
                            Id = 12,
                            ContactNumber = "651-787-4420 x344",
                            CreationTime = new DateTime(2019, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "denis_cormier@reichert.uk",
                            FirstName = "Felton",
                            LastName = "Russel"
                        },
                        new
                        {
                            Id = 13,
                            ContactNumber = "1-023-105-8284",
                            CreationTime = new DateTime(2019, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "kamron.oconner@monahankuphal.co.uk",
                            FirstName = "Austin",
                            LastName = "Stark"
                        },
                        new
                        {
                            Id = 14,
                            ContactNumber = "(232)025-5712",
                            CreationTime = new DateTime(2019, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "elmer_swaniawski@cormierhickle.com",
                            FirstName = "Liza",
                            LastName = "Torp"
                        },
                        new
                        {
                            Id = 15,
                            ContactNumber = "503-263-1363",
                            CreationTime = new DateTime(2019, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "vita@schamberger.co.uk",
                            FirstName = "Jalyn",
                            LastName = "Hoeger"
                        },
                        new
                        {
                            Id = 16,
                            ContactNumber = "346.232.8604 x17147",
                            CreationTime = new DateTime(2019, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "gunner_schowalter@feestkuvalis.uk",
                            FirstName = "Alysha",
                            LastName = "Sipes"
                        },
                        new
                        {
                            Id = 17,
                            ContactNumber = "320-602-3406",
                            CreationTime = new DateTime(2019, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "neha.bailey@marks.ca",
                            FirstName = "Jeanne",
                            LastName = "Tromp"
                        },
                        new
                        {
                            Id = 18,
                            ContactNumber = "(313)222-6782 x328",
                            CreationTime = new DateTime(2019, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mattie.kemmer@kub.co.uk",
                            FirstName = "Jovany",
                            LastName = "Gutmann"
                        },
                        new
                        {
                            Id = 19,
                            ContactNumber = "775.358.3677 x8260",
                            CreationTime = new DateTime(2019, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "meagan@runolfsson.us",
                            FirstName = "Rasheed",
                            LastName = "O'Kon"
                        },
                        new
                        {
                            Id = 20,
                            ContactNumber = "774-605-8226",
                            CreationTime = new DateTime(2019, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ivy_boyle@johnsonhayes.name",
                            FirstName = "Muhammad",
                            LastName = "Champlin"
                        },
                        new
                        {
                            Id = 21,
                            ContactNumber = "686-638-2312 x05674",
                            CreationTime = new DateTime(2019, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bryana@champlintrantow.ca",
                            FirstName = "Kiel",
                            LastName = "Aufderhar"
                        },
                        new
                        {
                            Id = 22,
                            ContactNumber = "555-632-3101",
                            CreationTime = new DateTime(2019, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "tate@balistreri.biz",
                            FirstName = "Marguerite",
                            LastName = "Lindgren"
                        },
                        new
                        {
                            Id = 23,
                            ContactNumber = "(476)282-1541 x203",
                            CreationTime = new DateTime(2019, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "berenice@hoppe.name",
                            FirstName = "Tillman",
                            LastName = "Bradtke"
                        },
                        new
                        {
                            Id = 24,
                            ContactNumber = "1-455-316-4155 x077",
                            CreationTime = new DateTime(2019, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "elinor_bayer@reinger.name",
                            FirstName = "Stone",
                            LastName = "Trantow"
                        },
                        new
                        {
                            Id = 25,
                            ContactNumber = "1-286-208-1552 x262",
                            CreationTime = new DateTime(2019, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "arnoldo_watsica@mertz.biz",
                            FirstName = "Verner",
                            LastName = "Braun"
                        },
                        new
                        {
                            Id = 26,
                            ContactNumber = "(787)115-5400",
                            CreationTime = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "viola@braun.uk",
                            FirstName = "Dorian",
                            LastName = "Bins"
                        },
                        new
                        {
                            Id = 27,
                            ContactNumber = "454.187.7035 x155",
                            CreationTime = new DateTime(2019, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "caesar.wisozk@jasthoeger.biz",
                            FirstName = "Jake",
                            LastName = "Ernser"
                        },
                        new
                        {
                            Id = 28,
                            ContactNumber = "778.577.0746",
                            CreationTime = new DateTime(2019, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jacynthe.sporer@hoeger.com",
                            FirstName = "Margot",
                            LastName = "Connelly"
                        },
                        new
                        {
                            Id = 29,
                            ContactNumber = "(421)760-0787 x422",
                            CreationTime = new DateTime(2019, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rick@frami.ca",
                            FirstName = "Stan",
                            LastName = "Welch"
                        },
                        new
                        {
                            Id = 30,
                            ContactNumber = "160.140.8142 x23364",
                            CreationTime = new DateTime(2019, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "barrett@smith.info",
                            FirstName = "Duane",
                            LastName = "Collier"
                        },
                        new
                        {
                            Id = 31,
                            ContactNumber = "564.226.3535 x13655",
                            CreationTime = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "sabrina@jacobson.name",
                            FirstName = "Maggie",
                            LastName = "Witting"
                        },
                        new
                        {
                            Id = 32,
                            ContactNumber = "134-341-4604 x6468",
                            CreationTime = new DateTime(2019, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "stephany_auer@mante.uk",
                            FirstName = "Ola",
                            LastName = "Conroy"
                        },
                        new
                        {
                            Id = 33,
                            ContactNumber = "026.868.3602 x7273",
                            CreationTime = new DateTime(2019, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mollie_botsford@lindgren.biz",
                            FirstName = "Jaeden",
                            LastName = "Schulist"
                        },
                        new
                        {
                            Id = 34,
                            ContactNumber = "(054)880-5612 x81770",
                            CreationTime = new DateTime(2019, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rozella@boyerhermiston.com",
                            FirstName = "Evans",
                            LastName = "Kshlerin"
                        },
                        new
                        {
                            Id = 35,
                            ContactNumber = "535.251.5337",
                            CreationTime = new DateTime(2019, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "roberto.corkery@rempelmertz.co.uk",
                            FirstName = "Filomena",
                            LastName = "West"
                        },
                        new
                        {
                            Id = 36,
                            ContactNumber = "1-420-418-1216 x5512",
                            CreationTime = new DateTime(2019, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "hassan.conn@murphy.co.uk",
                            FirstName = "D'angelo",
                            LastName = "Hoeger"
                        },
                        new
                        {
                            Id = 37,
                            ContactNumber = "(603)601-5511 x57413",
                            CreationTime = new DateTime(2019, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "elda@gottlieb.name",
                            FirstName = "Roy",
                            LastName = "Feest"
                        },
                        new
                        {
                            Id = 38,
                            ContactNumber = "1-282-616-2122",
                            CreationTime = new DateTime(2019, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "buster@hickle.co.uk",
                            FirstName = "Stacy",
                            LastName = "Schuster"
                        },
                        new
                        {
                            Id = 39,
                            ContactNumber = "655-724-4850 x872",
                            CreationTime = new DateTime(2019, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "joyce@treutel.uk",
                            FirstName = "Keeley",
                            LastName = "Bergstrom"
                        },
                        new
                        {
                            Id = 40,
                            ContactNumber = "1-528-228-4613 x735",
                            CreationTime = new DateTime(2019, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "eloise.lebsack@franecki.com",
                            FirstName = "Jana",
                            LastName = "Treutel"
                        },
                        new
                        {
                            Id = 41,
                            ContactNumber = "1-774-520-5420 x38814",
                            CreationTime = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "richard@kuphal.uk",
                            FirstName = "Elwyn",
                            LastName = "Kozey"
                        },
                        new
                        {
                            Id = 42,
                            ContactNumber = "(271)583-8333 x000",
                            CreationTime = new DateTime(2019, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "esteban.spencer@osinski.ca",
                            FirstName = "Rosario",
                            LastName = "Schuster"
                        },
                        new
                        {
                            Id = 43,
                            ContactNumber = "1-862-740-2851 x8238",
                            CreationTime = new DateTime(2019, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "maia@kovacekmorissette.info",
                            FirstName = "Kaylah",
                            LastName = "Krajcik"
                        },
                        new
                        {
                            Id = 44,
                            ContactNumber = "1-816-011-8862 x4510",
                            CreationTime = new DateTime(2019, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "tito@braun.uk",
                            FirstName = "Jace",
                            LastName = "Harris"
                        },
                        new
                        {
                            Id = 45,
                            ContactNumber = "778-040-8625",
                            CreationTime = new DateTime(2019, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "evan@romaguerabarton.com",
                            FirstName = "Tracey",
                            LastName = "Weber"
                        },
                        new
                        {
                            Id = 46,
                            ContactNumber = "287-315-2425",
                            CreationTime = new DateTime(2019, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "unique@becker.com",
                            FirstName = "Remington",
                            LastName = "Rosenbaum"
                        },
                        new
                        {
                            Id = 47,
                            ContactNumber = "875-281-6412 x825",
                            CreationTime = new DateTime(2019, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mellie.yost@stiedemannhettinger.com",
                            FirstName = "Clinton",
                            LastName = "Cruickshank"
                        },
                        new
                        {
                            Id = 48,
                            ContactNumber = "(862)247-7853",
                            CreationTime = new DateTime(2019, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "hildegard@morarhoeger.name",
                            FirstName = "Joany",
                            LastName = "Mraz"
                        },
                        new
                        {
                            Id = 49,
                            ContactNumber = "060.203.0853",
                            CreationTime = new DateTime(2019, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "cleta.dare@hesselhackett.name",
                            FirstName = "Waylon",
                            LastName = "Schimmel"
                        },
                        new
                        {
                            Id = 50,
                            ContactNumber = "1-305-232-6317",
                            CreationTime = new DateTime(2019, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "halle@mante.info",
                            FirstName = "Germaine",
                            LastName = "Wisozk"
                        },
                        new
                        {
                            Id = 51,
                            ContactNumber = "1-482-571-8272 x00570",
                            CreationTime = new DateTime(2019, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "marjorie.bednar@bergstrom.ca",
                            FirstName = "Fidel",
                            LastName = "Corkery"
                        },
                        new
                        {
                            Id = 52,
                            ContactNumber = "251.587.3431 x3603",
                            CreationTime = new DateTime(2019, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "torey@bayer.info",
                            FirstName = "Jacinthe",
                            LastName = "Jast"
                        },
                        new
                        {
                            Id = 53,
                            ContactNumber = "1-622-371-3614 x36556",
                            CreationTime = new DateTime(2019, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "desmond@heller.ca",
                            FirstName = "Kurtis",
                            LastName = "Blick"
                        },
                        new
                        {
                            Id = 54,
                            ContactNumber = "203.345.5116 x42535",
                            CreationTime = new DateTime(2019, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "torey@gerlachgulgowski.biz",
                            FirstName = "Donnie",
                            LastName = "Rodriguez"
                        },
                        new
                        {
                            Id = 55,
                            ContactNumber = "1-385-523-3343",
                            CreationTime = new DateTime(2019, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rodrick@adams.info",
                            FirstName = "Monte",
                            LastName = "Hoeger"
                        },
                        new
                        {
                            Id = 56,
                            ContactNumber = "1-034-850-6004 x25508",
                            CreationTime = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "al_wintheiser@hammes.us",
                            FirstName = "Chelsea",
                            LastName = "Larson"
                        },
                        new
                        {
                            Id = 57,
                            ContactNumber = "826-441-3204 x601",
                            CreationTime = new DateTime(2019, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "enrique.brekke@medhurst.info",
                            FirstName = "Cletus",
                            LastName = "Rempel"
                        },
                        new
                        {
                            Id = 58,
                            ContactNumber = "1-816-586-1675 x772",
                            CreationTime = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "marina.emard@will.info",
                            FirstName = "Alex",
                            LastName = "Nikolaus"
                        },
                        new
                        {
                            Id = 59,
                            ContactNumber = "651.545.8515 x24722",
                            CreationTime = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "vincent@lang.ca",
                            FirstName = "Randy",
                            LastName = "Dickinson"
                        },
                        new
                        {
                            Id = 60,
                            ContactNumber = "280-041-0345 x108",
                            CreationTime = new DateTime(2019, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "elizabeth@wiegand.co.uk",
                            FirstName = "Augustine",
                            LastName = "Cartwright"
                        },
                        new
                        {
                            Id = 61,
                            ContactNumber = "(345)735-2345 x46355",
                            CreationTime = new DateTime(2019, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "annette.lowe@williamson.com",
                            FirstName = "Heber",
                            LastName = "Heidenreich"
                        },
                        new
                        {
                            Id = 62,
                            ContactNumber = "1-472-860-3543 x67300",
                            CreationTime = new DateTime(2019, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "kenyatta@effertzrowe.biz",
                            FirstName = "Filiberto",
                            LastName = "Stanton"
                        },
                        new
                        {
                            Id = 63,
                            ContactNumber = "1-073-813-3346",
                            CreationTime = new DateTime(2019, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "liliane.oconnell@okuneva.co.uk",
                            FirstName = "Grady",
                            LastName = "Christiansen"
                        },
                        new
                        {
                            Id = 64,
                            ContactNumber = "177-045-1010",
                            CreationTime = new DateTime(2019, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "clemmie_sipes@kub.co.uk",
                            FirstName = "Gavin",
                            LastName = "Haag"
                        },
                        new
                        {
                            Id = 65,
                            ContactNumber = "(248)874-7626 x7765",
                            CreationTime = new DateTime(2019, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "beulah@russel.ca",
                            FirstName = "Ethel",
                            LastName = "Gleason"
                        },
                        new
                        {
                            Id = 66,
                            ContactNumber = "688.458.2884 x43057",
                            CreationTime = new DateTime(2019, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "elena.sauer@hintz.co.uk",
                            FirstName = "Mauricio",
                            LastName = "Wehner"
                        },
                        new
                        {
                            Id = 67,
                            ContactNumber = "(207)154-0175",
                            CreationTime = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "arvid@johnsonstark.name",
                            FirstName = "Isaiah",
                            LastName = "Glover"
                        },
                        new
                        {
                            Id = 68,
                            ContactNumber = "(028)610-8056 x7803",
                            CreationTime = new DateTime(2019, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "anahi_cole@walterstanton.co.uk",
                            FirstName = "Carroll",
                            LastName = "Becker"
                        },
                        new
                        {
                            Id = 69,
                            ContactNumber = "833-441-8072",
                            CreationTime = new DateTime(2019, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "elwin.pagac@pfeffer.uk",
                            FirstName = "Hannah",
                            LastName = "Weimann"
                        },
                        new
                        {
                            Id = 70,
                            ContactNumber = "(266)386-6178 x7061",
                            CreationTime = new DateTime(2019, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "juanita.bernhard@shieldsstokes.com",
                            FirstName = "Joshua",
                            LastName = "Beer"
                        },
                        new
                        {
                            Id = 71,
                            ContactNumber = "1-542-225-8736 x6615",
                            CreationTime = new DateTime(2019, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "connor@zemlak.us",
                            FirstName = "Ben",
                            LastName = "Paucek"
                        },
                        new
                        {
                            Id = 72,
                            ContactNumber = "1-103-027-0505 x324",
                            CreationTime = new DateTime(2019, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jaylon.wiza@halvorson.name",
                            FirstName = "Mason",
                            LastName = "Langosh"
                        },
                        new
                        {
                            Id = 73,
                            ContactNumber = "(158)275-4786 x022",
                            CreationTime = new DateTime(2019, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lysanne_okon@nikolaus.com",
                            FirstName = "Ross",
                            LastName = "Herman"
                        },
                        new
                        {
                            Id = 74,
                            ContactNumber = "401-130-5267",
                            CreationTime = new DateTime(2019, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "leola_schmitt@kohler.us",
                            FirstName = "Aric",
                            LastName = "Parker"
                        },
                        new
                        {
                            Id = 75,
                            ContactNumber = "804.677.1720",
                            CreationTime = new DateTime(2019, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "timmy_schamberger@hackettkuhlman.name",
                            FirstName = "Pete",
                            LastName = "Schulist"
                        },
                        new
                        {
                            Id = 76,
                            ContactNumber = "380-672-1366 x7120",
                            CreationTime = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "maddison@franeckirodriguez.co.uk",
                            FirstName = "Beth",
                            LastName = "Rosenbaum"
                        },
                        new
                        {
                            Id = 77,
                            ContactNumber = "(680)007-0460 x54040",
                            CreationTime = new DateTime(2019, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "loyce.koelpin@harrisbechtelar.biz",
                            FirstName = "Rosemarie",
                            LastName = "Mitchell"
                        },
                        new
                        {
                            Id = 78,
                            ContactNumber = "585.356.7136",
                            CreationTime = new DateTime(2019, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "cleta.lakin@erdman.biz",
                            FirstName = "Harmon",
                            LastName = "Rohan"
                        },
                        new
                        {
                            Id = 79,
                            ContactNumber = "420-030-4515",
                            CreationTime = new DateTime(2019, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "marlee@champlin.us",
                            FirstName = "Joaquin",
                            LastName = "Wilkinson"
                        },
                        new
                        {
                            Id = 80,
                            ContactNumber = "(803)138-8717 x5623",
                            CreationTime = new DateTime(2019, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "gerhard@gibsonmcdermott.uk",
                            FirstName = "Gregoria",
                            LastName = "Schoen"
                        },
                        new
                        {
                            Id = 81,
                            ContactNumber = "418.324.3868 x7811",
                            CreationTime = new DateTime(2019, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "major@keebler.uk",
                            FirstName = "Phyllis",
                            LastName = "Mohr"
                        },
                        new
                        {
                            Id = 82,
                            ContactNumber = "026.640.7383 x27044",
                            CreationTime = new DateTime(2019, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ernest_wilderman@rippin.us",
                            FirstName = "Ofelia",
                            LastName = "O'Hara"
                        },
                        new
                        {
                            Id = 83,
                            ContactNumber = "385-187-1715 x7778",
                            CreationTime = new DateTime(2019, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "sydney_schmidt@blickcole.biz",
                            FirstName = "Damion",
                            LastName = "Erdman"
                        },
                        new
                        {
                            Id = 84,
                            ContactNumber = "(772)573-4243 x4213",
                            CreationTime = new DateTime(2019, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "tate_hackett@larkin.co.uk",
                            FirstName = "Patricia",
                            LastName = "Shields"
                        },
                        new
                        {
                            Id = 85,
                            ContactNumber = "1-747-146-1741 x072",
                            CreationTime = new DateTime(2019, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "candelario@metz.ca",
                            FirstName = "Salma",
                            LastName = "Fadel"
                        },
                        new
                        {
                            Id = 86,
                            ContactNumber = "(431)436-2768 x000",
                            CreationTime = new DateTime(2019, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lydia.wuckert@gutmannkihn.biz",
                            FirstName = "Alta",
                            LastName = "O'Connell"
                        },
                        new
                        {
                            Id = 87,
                            ContactNumber = "388-226-2172",
                            CreationTime = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "isaias@ziemann.ca",
                            FirstName = "Catalina",
                            LastName = "Treutel"
                        },
                        new
                        {
                            Id = 88,
                            ContactNumber = "712-254-3861",
                            CreationTime = new DateTime(2019, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "elenor_collier@hirthe.co.uk",
                            FirstName = "Miguel",
                            LastName = "Koelpin"
                        },
                        new
                        {
                            Id = 89,
                            ContactNumber = "(716)711-8278 x8671",
                            CreationTime = new DateTime(2019, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "nasir@mcculloughschinner.us",
                            FirstName = "Katelynn",
                            LastName = "Zboncak"
                        },
                        new
                        {
                            Id = 90,
                            ContactNumber = "(468)788-5314 x3004",
                            CreationTime = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ima@kassulke.name",
                            FirstName = "Giles",
                            LastName = "Kessler"
                        },
                        new
                        {
                            Id = 91,
                            ContactNumber = "688.514.6623 x420",
                            CreationTime = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ellsworth@gleichner.ca",
                            FirstName = "Destiney",
                            LastName = "VonRueden"
                        },
                        new
                        {
                            Id = 92,
                            ContactNumber = "(111)114-7653 x512",
                            CreationTime = new DateTime(2019, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "zella.lakin@jewess.ca",
                            FirstName = "Nedra",
                            LastName = "Fay"
                        },
                        new
                        {
                            Id = 93,
                            ContactNumber = "103-366-1317 x638",
                            CreationTime = new DateTime(2019, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "domenic@lubowitz.biz",
                            FirstName = "Jermain",
                            LastName = "Gusikowski"
                        },
                        new
                        {
                            Id = 94,
                            ContactNumber = "086-524-3568 x784",
                            CreationTime = new DateTime(2019, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "felipa_paucek@schultzbergnaum.co.uk",
                            FirstName = "Sandrine",
                            LastName = "Balistreri"
                        },
                        new
                        {
                            Id = 95,
                            ContactNumber = "518.463.5415 x248",
                            CreationTime = new DateTime(2019, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rogelio@sanford.ca",
                            FirstName = "Dianna",
                            LastName = "Welch"
                        },
                        new
                        {
                            Id = 96,
                            ContactNumber = "218.320.8278 x1014",
                            CreationTime = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "peter.gislason@skiles.us",
                            FirstName = "Caleigh",
                            LastName = "Hoeger"
                        },
                        new
                        {
                            Id = 97,
                            ContactNumber = "582.713.3136 x278",
                            CreationTime = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jed@gislason.ca",
                            FirstName = "Schuyler",
                            LastName = "Trantow"
                        },
                        new
                        {
                            Id = 98,
                            ContactNumber = "(383)628-4802 x0761",
                            CreationTime = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jaren_lebsack@steuber.ca",
                            FirstName = "Sadye",
                            LastName = "Botsford"
                        },
                        new
                        {
                            Id = 99,
                            ContactNumber = "(655)730-4843 x33145",
                            CreationTime = new DateTime(2019, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mallory@reilly.us",
                            FirstName = "Zora",
                            LastName = "Greenfelder"
                        },
                        new
                        {
                            Id = 100,
                            ContactNumber = "812-752-3431 x82180",
                            CreationTime = new DateTime(2019, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "nicola@gottlieb.us",
                            FirstName = "Joe",
                            LastName = "Schiller"
                        });
                });

            modelBuilder.Entity("Rental.Core.Entities.GameRental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BoardGameId");

                    b.Property<float>("ChargedDeposit");

                    b.Property<int>("ClientId");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 8, 7, 7, 50, 13, 762, DateTimeKind.Utc).AddTicks(241));

                    b.Property<float>("PaidMoney");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("BoardGameId");

                    b.HasIndex("ClientId");

                    b.ToTable("GameRentals");
                });

            modelBuilder.Entity("Rental.Core.Entities.GameRental", b =>
                {
                    b.HasOne("Rental.Core.Entities.BoardGame", "BoardGame")
                        .WithMany("GameRentals")
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rental.Core.Entities.Client", "Client")
                        .WithMany("GameRentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
