// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rental.DataAccess.Context;

namespace Rental.DataAccess.Migrations
{
    [DbContext(typeof(RentalContext))]
    partial class RentalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("r")
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6");

            modelBuilder.Entity("Rental.DataAccess.Entities.BoardGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 8, 10, 8, 12, 45, 152, DateTimeKind.Utc).AddTicks(5828));

                    b.Property<string>("Name");

                    b.Property<float>("Price");

                    b.HasKey("Id");

                    b.ToTable("BoardGames");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b520c0d-e617-4177-819a-f207df11b8d2"),
                            CreationTime = new DateTime(2019, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 171f
                        },
                        new
                        {
                            Id = new Guid("9b7d3051-a14c-4bf2-9d5e-0ba507d6e922"),
                            CreationTime = new DateTime(2019, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 126f
                        },
                        new
                        {
                            Id = new Guid("b62d9e4a-1941-46a0-aa13-8a3866b3f222"),
                            CreationTime = new DateTime(2019, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 139f
                        },
                        new
                        {
                            Id = new Guid("cec32491-c16c-4348-a640-88151d52186c"),
                            CreationTime = new DateTime(2019, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 149f
                        },
                        new
                        {
                            Id = new Guid("8d6591f6-22a6-4a2a-b12e-047771d05381"),
                            CreationTime = new DateTime(2019, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 185f
                        },
                        new
                        {
                            Id = new Guid("397ebf00-6913-4c73-9363-2d7d4721eb08"),
                            CreationTime = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 136f
                        },
                        new
                        {
                            Id = new Guid("8ac2d142-a41f-490f-8f9d-95528dac370c"),
                            CreationTime = new DateTime(2019, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 219f
                        },
                        new
                        {
                            Id = new Guid("75997922-06ba-4b7f-a13d-d9a73583e826"),
                            CreationTime = new DateTime(2019, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 61f
                        },
                        new
                        {
                            Id = new Guid("f59e1fff-8156-48f4-a99d-dd119ac49bce"),
                            CreationTime = new DateTime(2019, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 215f
                        },
                        new
                        {
                            Id = new Guid("14339d1a-90ad-40b9-a281-b6398e9a6ae9"),
                            CreationTime = new DateTime(2019, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 82f
                        },
                        new
                        {
                            Id = new Guid("0ab80e9d-9b85-492c-a937-b216436edbdb"),
                            CreationTime = new DateTime(2019, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 154f
                        },
                        new
                        {
                            Id = new Guid("a1dfe9d3-4d83-46e5-a91e-ed6c3ac877c6"),
                            CreationTime = new DateTime(2019, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 174f
                        },
                        new
                        {
                            Id = new Guid("ba295d35-db43-4bc3-9bb4-e510f5563dc0"),
                            CreationTime = new DateTime(2019, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 90f
                        },
                        new
                        {
                            Id = new Guid("63fa3100-8b42-4f3d-aae0-e9c1f62f46e2"),
                            CreationTime = new DateTime(2019, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 169f
                        },
                        new
                        {
                            Id = new Guid("beec1f8c-3c3d-4880-a13b-2e60b3ccc0c7"),
                            CreationTime = new DateTime(2019, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 116f
                        },
                        new
                        {
                            Id = new Guid("cb15dff5-5897-490b-8a5c-2652ccc19979"),
                            CreationTime = new DateTime(2019, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 92f
                        },
                        new
                        {
                            Id = new Guid("ff3d42f8-01b9-477c-8a00-6edf1ce68151"),
                            CreationTime = new DateTime(2019, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 136f
                        },
                        new
                        {
                            Id = new Guid("22633af9-1b38-4247-931c-1000c9e2f6a0"),
                            CreationTime = new DateTime(2019, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 181f
                        },
                        new
                        {
                            Id = new Guid("d1dd49bb-167e-4285-b7db-93c5838fa88e"),
                            CreationTime = new DateTime(2019, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 175f
                        },
                        new
                        {
                            Id = new Guid("722f6671-c4fd-4e4c-b0d9-936df4cc2b05"),
                            CreationTime = new DateTime(2019, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 194f
                        },
                        new
                        {
                            Id = new Guid("3a8a9442-dd2a-4bf3-8f1d-c9fe90fc7625"),
                            CreationTime = new DateTime(2019, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 193f
                        },
                        new
                        {
                            Id = new Guid("035f216a-2a02-4afa-a97b-8755b1c91dd3"),
                            CreationTime = new DateTime(2019, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 200f
                        },
                        new
                        {
                            Id = new Guid("edfc0278-2283-45fa-8577-3240d6c8aeee"),
                            CreationTime = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 235f
                        },
                        new
                        {
                            Id = new Guid("4118cce1-e003-4e1c-b9b5-ff00efce3794"),
                            CreationTime = new DateTime(2019, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 242f
                        },
                        new
                        {
                            Id = new Guid("880db061-2419-487a-8f80-b987589dafd7"),
                            CreationTime = new DateTime(2019, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 245f
                        },
                        new
                        {
                            Id = new Guid("ab56a09b-9da4-4c71-ab93-04011442d98f"),
                            CreationTime = new DateTime(2019, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 217f
                        },
                        new
                        {
                            Id = new Guid("10524936-9449-4f81-af67-9ef4274b08fb"),
                            CreationTime = new DateTime(2019, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 117f
                        },
                        new
                        {
                            Id = new Guid("62b73688-717f-4123-939a-dc26a606bfd5"),
                            CreationTime = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 160f
                        },
                        new
                        {
                            Id = new Guid("f2ac557f-9402-4809-8571-3b426e0051a5"),
                            CreationTime = new DateTime(2019, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 114f
                        },
                        new
                        {
                            Id = new Guid("1ef30a64-c609-46ab-9b68-ff73938cb6d7"),
                            CreationTime = new DateTime(2019, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 105f
                        },
                        new
                        {
                            Id = new Guid("eb2896d5-3b1e-4b6b-bebc-adbdfaeb96fc"),
                            CreationTime = new DateTime(2019, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 129f
                        },
                        new
                        {
                            Id = new Guid("3a542649-bd35-4080-b8bd-f79967102f8e"),
                            CreationTime = new DateTime(2019, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 224f
                        },
                        new
                        {
                            Id = new Guid("43c8ad8f-a40e-44ce-b5a0-e765e4579dde"),
                            CreationTime = new DateTime(2019, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 152f
                        },
                        new
                        {
                            Id = new Guid("d9eb39d0-e0a2-4d2d-81c0-0e81de5ce746"),
                            CreationTime = new DateTime(2019, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 136f
                        },
                        new
                        {
                            Id = new Guid("aa5e626a-0acb-4bd0-aaf8-e766421c7a7e"),
                            CreationTime = new DateTime(2019, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 70f
                        },
                        new
                        {
                            Id = new Guid("d0e9bc02-0188-4817-b740-0407c6f090bc"),
                            CreationTime = new DateTime(2019, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 78f
                        },
                        new
                        {
                            Id = new Guid("d6caeeb8-9b60-49fa-81da-c7f9b38a61c5"),
                            CreationTime = new DateTime(2019, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 156f
                        },
                        new
                        {
                            Id = new Guid("d5aaf428-8b06-43bb-b7d2-85f1fd43af3f"),
                            CreationTime = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 160f
                        },
                        new
                        {
                            Id = new Guid("eb9b245e-00aa-48be-b3a0-cabdc70dac80"),
                            CreationTime = new DateTime(2019, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 217f
                        },
                        new
                        {
                            Id = new Guid("bcecf1e4-643c-4b04-8ad3-e290f07353f2"),
                            CreationTime = new DateTime(2019, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 185f
                        },
                        new
                        {
                            Id = new Guid("59c13895-4e20-484b-8eb7-93d2610e6bbd"),
                            CreationTime = new DateTime(2019, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 196f
                        },
                        new
                        {
                            Id = new Guid("f0cd7d30-f102-4e60-9e99-b231908abaa3"),
                            CreationTime = new DateTime(2019, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 104f
                        },
                        new
                        {
                            Id = new Guid("32939fdb-e2ee-42e7-bba5-27ec1363d77f"),
                            CreationTime = new DateTime(2019, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 151f
                        },
                        new
                        {
                            Id = new Guid("d082d6dc-e131-47e5-a3a8-aec03d9d0b84"),
                            CreationTime = new DateTime(2019, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 173f
                        },
                        new
                        {
                            Id = new Guid("3da1f12f-b728-4080-ad40-52a4a1575157"),
                            CreationTime = new DateTime(2019, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 60f
                        },
                        new
                        {
                            Id = new Guid("fcb91a87-70ec-4b92-bf4b-8a3d8af13eab"),
                            CreationTime = new DateTime(2019, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 188f
                        },
                        new
                        {
                            Id = new Guid("f4bdee88-ad9b-4356-ac13-06feee71affe"),
                            CreationTime = new DateTime(2019, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 216f
                        },
                        new
                        {
                            Id = new Guid("892bf472-3b8d-4cbd-acf7-4362e0acc582"),
                            CreationTime = new DateTime(2019, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 236f
                        },
                        new
                        {
                            Id = new Guid("2d0be64a-913c-4295-b5dc-b24bbdd016c1"),
                            CreationTime = new DateTime(2019, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 229f
                        },
                        new
                        {
                            Id = new Guid("55c03535-8f90-4b36-9981-d546b6bf1131"),
                            CreationTime = new DateTime(2019, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 246f
                        },
                        new
                        {
                            Id = new Guid("778692cb-2711-4bbe-baf5-558d9b67935f"),
                            CreationTime = new DateTime(2019, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 134f
                        },
                        new
                        {
                            Id = new Guid("b7866594-a9a0-4c2d-adcf-2747f8e5757d"),
                            CreationTime = new DateTime(2019, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 248f
                        },
                        new
                        {
                            Id = new Guid("5cdc4db4-1633-4744-a2d9-f95109453f40"),
                            CreationTime = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 135f
                        },
                        new
                        {
                            Id = new Guid("718732dd-f3f7-45ae-99b4-d8b71c7c7d88"),
                            CreationTime = new DateTime(2019, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 243f
                        },
                        new
                        {
                            Id = new Guid("660b9043-906e-4c9b-92a4-7795e520798a"),
                            CreationTime = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 226f
                        },
                        new
                        {
                            Id = new Guid("c4d7eab1-e7e8-494c-b2ba-0e211c5fb89a"),
                            CreationTime = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 220f
                        },
                        new
                        {
                            Id = new Guid("92f0f9f0-712b-42b0-9067-695d7173ff64"),
                            CreationTime = new DateTime(2019, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 140f
                        },
                        new
                        {
                            Id = new Guid("a0780bb9-6f11-46a0-a629-bd365cd374c1"),
                            CreationTime = new DateTime(2019, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 146f
                        },
                        new
                        {
                            Id = new Guid("ed42836f-78b4-4bc7-8cfc-60a96c14290b"),
                            CreationTime = new DateTime(2019, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 154f
                        },
                        new
                        {
                            Id = new Guid("11705fe5-da6c-4861-bff0-984927133995"),
                            CreationTime = new DateTime(2019, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 217f
                        },
                        new
                        {
                            Id = new Guid("4bbf2329-ac15-4903-b035-77640ac0ba89"),
                            CreationTime = new DateTime(2019, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 69f
                        },
                        new
                        {
                            Id = new Guid("e7d964e7-f45c-4b53-97f3-a7bccba7ce7e"),
                            CreationTime = new DateTime(2019, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 109f
                        },
                        new
                        {
                            Id = new Guid("a662e707-e767-4313-be42-30c0166b3eb4"),
                            CreationTime = new DateTime(2019, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 197f
                        },
                        new
                        {
                            Id = new Guid("c32f5bad-2a92-4588-bc9c-1bacdcb679f4"),
                            CreationTime = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 159f
                        },
                        new
                        {
                            Id = new Guid("f0b75d26-ff8e-497f-8c97-d64b04563763"),
                            CreationTime = new DateTime(2019, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 202f
                        },
                        new
                        {
                            Id = new Guid("056846eb-1a7c-4155-8c58-f2ce6d1dbb2a"),
                            CreationTime = new DateTime(2019, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 179f
                        },
                        new
                        {
                            Id = new Guid("23e5b31f-3285-4d8c-89e7-c9d8a93f32d1"),
                            CreationTime = new DateTime(2019, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 71f
                        },
                        new
                        {
                            Id = new Guid("de3dbb5a-4b79-4c3c-a0a9-9d05f773ac88"),
                            CreationTime = new DateTime(2019, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 204f
                        },
                        new
                        {
                            Id = new Guid("aabf02b8-ca9b-471d-96c3-d34ca069cef8"),
                            CreationTime = new DateTime(2019, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 149f
                        },
                        new
                        {
                            Id = new Guid("58545c0d-d84a-413f-98dd-749d37f958c0"),
                            CreationTime = new DateTime(2019, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 88f
                        },
                        new
                        {
                            Id = new Guid("ae0bd5a1-4542-413e-bbcc-13ee1c02b901"),
                            CreationTime = new DateTime(2019, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 186f
                        },
                        new
                        {
                            Id = new Guid("e0512599-ab0a-4eea-9906-f2efb847e723"),
                            CreationTime = new DateTime(2019, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 226f
                        },
                        new
                        {
                            Id = new Guid("ea861bc4-3ad7-4b07-ae0c-8ef352dc4b55"),
                            CreationTime = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 214f
                        },
                        new
                        {
                            Id = new Guid("f82412db-4533-48c7-bc77-ff224f1c8459"),
                            CreationTime = new DateTime(2019, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 240f
                        },
                        new
                        {
                            Id = new Guid("040f56c0-fa46-481b-a705-6b212483473a"),
                            CreationTime = new DateTime(2019, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 248f
                        },
                        new
                        {
                            Id = new Guid("bc0b137f-38eb-40de-a562-53d10d09417a"),
                            CreationTime = new DateTime(2019, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 138f
                        },
                        new
                        {
                            Id = new Guid("69ea40af-07a7-4634-ad33-fd9542c6a486"),
                            CreationTime = new DateTime(2019, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 99f
                        },
                        new
                        {
                            Id = new Guid("65a8e051-dca0-4521-91ac-3c551690d4dd"),
                            CreationTime = new DateTime(2019, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 111f
                        },
                        new
                        {
                            Id = new Guid("4974c94c-e09c-4d38-b4b8-46b541f4d81f"),
                            CreationTime = new DateTime(2019, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 232f
                        },
                        new
                        {
                            Id = new Guid("e7f52fe8-ef7c-4685-9adf-f01db995c5a6"),
                            CreationTime = new DateTime(2019, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 106f
                        },
                        new
                        {
                            Id = new Guid("5bff8334-0677-4fde-87f0-994b328e6590"),
                            CreationTime = new DateTime(2019, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 50f
                        },
                        new
                        {
                            Id = new Guid("5026e78f-5e4d-44a9-9015-8346ee76ef56"),
                            CreationTime = new DateTime(2019, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 130f
                        },
                        new
                        {
                            Id = new Guid("f960d86a-a2e6-49ef-ac90-532cfe1d2a50"),
                            CreationTime = new DateTime(2019, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 180f
                        },
                        new
                        {
                            Id = new Guid("6d88432c-45b0-46c5-bcf4-2ce5849cfc7a"),
                            CreationTime = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 118f
                        },
                        new
                        {
                            Id = new Guid("0da4e6bb-6433-46c3-9e96-b958b78e52ca"),
                            CreationTime = new DateTime(2019, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 221f
                        },
                        new
                        {
                            Id = new Guid("217eed19-6630-4df4-928b-6f0e0b03b25d"),
                            CreationTime = new DateTime(2019, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 130f
                        },
                        new
                        {
                            Id = new Guid("e621424e-9463-4e1b-b7ff-db7f8d78e0eb"),
                            CreationTime = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 139f
                        },
                        new
                        {
                            Id = new Guid("7636539e-3ef4-4c7c-b12e-c07d81c0ad4c"),
                            CreationTime = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 158f
                        },
                        new
                        {
                            Id = new Guid("a3a0171c-22dd-4003-877e-2f5fc5bad132"),
                            CreationTime = new DateTime(2019, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 160f
                        },
                        new
                        {
                            Id = new Guid("c95c7c33-5ef5-4fa7-9839-1765e9d9c9ff"),
                            CreationTime = new DateTime(2019, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 99f
                        },
                        new
                        {
                            Id = new Guid("aafcf2a7-c930-49fd-9521-9f1266e9af1c"),
                            CreationTime = new DateTime(2019, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 187f
                        },
                        new
                        {
                            Id = new Guid("a5c4e918-52fa-416b-b444-697cef39ee05"),
                            CreationTime = new DateTime(2019, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 59f
                        },
                        new
                        {
                            Id = new Guid("ceca74b1-093e-4c24-91e1-49033590f2fb"),
                            CreationTime = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 55f
                        },
                        new
                        {
                            Id = new Guid("171108b6-1ad0-4e76-8a7a-647206528c95"),
                            CreationTime = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 249f
                        },
                        new
                        {
                            Id = new Guid("5d1c7e2d-a756-4831-b031-cf972e14502e"),
                            CreationTime = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 166f
                        },
                        new
                        {
                            Id = new Guid("5983ccc6-5814-4b4e-93e0-9030e0261f4a"),
                            CreationTime = new DateTime(2019, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 137f
                        },
                        new
                        {
                            Id = new Guid("d9848079-6682-45b8-976e-a2b383efa2ac"),
                            CreationTime = new DateTime(2019, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 157f
                        },
                        new
                        {
                            Id = new Guid("d3ae3b54-1d25-4623-9fb1-1f661bb483d3"),
                            CreationTime = new DateTime(2019, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 241f
                        },
                        new
                        {
                            Id = new Guid("d5f34d20-a807-4216-84fc-2ce2d2aad501"),
                            CreationTime = new DateTime(2019, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 220f
                        },
                        new
                        {
                            Id = new Guid("56fd6cd4-def5-4e4f-9cdf-8309594acac8"),
                            CreationTime = new DateTime(2019, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "alias",
                            Price = 130f
                        });
                });

            modelBuilder.Entity("Rental.DataAccess.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactNumber");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 8, 10, 8, 12, 45, 156, DateTimeKind.Utc).AddTicks(6863));

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("adedfe27-7c7e-4632-a054-fcae697360c4"),
                            ContactNumber = "355.380.3225",
                            CreationTime = new DateTime(2019, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "moises.waters@abshire.info",
                            FirstName = "Mylene",
                            LastName = "Schneider"
                        },
                        new
                        {
                            Id = new Guid("e20b7edf-9a74-417d-9fd0-a18481892789"),
                            ContactNumber = "220-650-8050",
                            CreationTime = new DateTime(2019, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "khalid@kutch.info",
                            FirstName = "Ernest",
                            LastName = "Howell"
                        },
                        new
                        {
                            Id = new Guid("7cecd19e-cdbf-45ea-b16e-88fc737d1e15"),
                            ContactNumber = "1-552-500-4600 x7471",
                            CreationTime = new DateTime(2019, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "evangeline@donnellykuvalis.us",
                            FirstName = "Kiera",
                            LastName = "Mann"
                        },
                        new
                        {
                            Id = new Guid("317cadd6-6e7a-49fa-a32a-2f891d811604"),
                            ContactNumber = "635.826.3026 x55503",
                            CreationTime = new DateTime(2019, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jayson_ebert@muller.info",
                            FirstName = "Dina",
                            LastName = "Feest"
                        },
                        new
                        {
                            Id = new Guid("ea423887-21da-49cf-8e5d-1ec550de5e5a"),
                            ContactNumber = "1-150-243-5424 x01060",
                            CreationTime = new DateTime(2019, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "michael.marks@hahn.co.uk",
                            FirstName = "Nikki",
                            LastName = "Corkery"
                        },
                        new
                        {
                            Id = new Guid("76994781-ea13-4e2e-9f96-5a00e525d628"),
                            ContactNumber = "(344)721-7132",
                            CreationTime = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "casimer@walter.com",
                            FirstName = "Marley",
                            LastName = "Bednar"
                        },
                        new
                        {
                            Id = new Guid("48e679fc-c85b-4c5f-86eb-5fe09489b7a9"),
                            ContactNumber = "125-515-1351 x805",
                            CreationTime = new DateTime(2019, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "candida@wuckert.ca",
                            FirstName = "Carmine",
                            LastName = "Huels"
                        },
                        new
                        {
                            Id = new Guid("bbe3fffc-2563-4db3-ae3d-b52dd08b9d3e"),
                            ContactNumber = "453.283.7773",
                            CreationTime = new DateTime(2019, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "dejuan_wunsch@weber.co.uk",
                            FirstName = "Rosie",
                            LastName = "Wolff"
                        },
                        new
                        {
                            Id = new Guid("c6cf1dfc-17ee-4a92-a690-0037b82c2fe9"),
                            ContactNumber = "417-605-4354",
                            CreationTime = new DateTime(2019, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "amalia@auer.ca",
                            FirstName = "Quinn",
                            LastName = "Gaylord"
                        },
                        new
                        {
                            Id = new Guid("7efff820-4e51-4424-b11d-ea5887d21263"),
                            ContactNumber = "353.351.4042 x7184",
                            CreationTime = new DateTime(2019, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "camren@gerholdhand.com",
                            FirstName = "Rasheed",
                            LastName = "Lehner"
                        },
                        new
                        {
                            Id = new Guid("afa9708c-f0b6-4b5c-97bd-4a2413fb4881"),
                            ContactNumber = "077-165-3622 x45764",
                            CreationTime = new DateTime(2019, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "seamus@koss.us",
                            FirstName = "Elisha",
                            LastName = "Jacobs"
                        },
                        new
                        {
                            Id = new Guid("4733eaf7-d724-4120-94a3-6d3ad4354ae0"),
                            ContactNumber = "1-271-534-2486",
                            CreationTime = new DateTime(2019, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "kenton@willms.co.uk",
                            FirstName = "Neva",
                            LastName = "Grant"
                        },
                        new
                        {
                            Id = new Guid("d084913b-3a9c-4075-951e-180216512d7d"),
                            ContactNumber = "1-372-370-4174 x52458",
                            CreationTime = new DateTime(2019, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "julia_harvey@wilkinson.com",
                            FirstName = "Llewellyn",
                            LastName = "Lueilwitz"
                        },
                        new
                        {
                            Id = new Guid("453800ed-aeab-4e88-a32b-2efa31262e26"),
                            ContactNumber = "820-751-3645 x662",
                            CreationTime = new DateTime(2019, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "claudine@langoshcorkery.co.uk",
                            FirstName = "Henderson",
                            LastName = "Wintheiser"
                        },
                        new
                        {
                            Id = new Guid("feafd2a0-fad3-41a1-ac92-4aa40a5a0e04"),
                            ContactNumber = "872-278-3108",
                            CreationTime = new DateTime(2019, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "martin_stanton@murazik.co.uk",
                            FirstName = "Antonette",
                            LastName = "Bruen"
                        },
                        new
                        {
                            Id = new Guid("b6eeb74b-f3a1-4520-a71e-0e094bd2b27c"),
                            ContactNumber = "700-663-1038",
                            CreationTime = new DateTime(2019, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "santino@emard.us",
                            FirstName = "Thora",
                            LastName = "Klein"
                        },
                        new
                        {
                            Id = new Guid("7de13653-8ec2-4eb7-9fdd-622ac9e6d4e1"),
                            ContactNumber = "1-246-854-3872",
                            CreationTime = new DateTime(2019, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "vincent.mclaughlin@bode.co.uk",
                            FirstName = "Gertrude",
                            LastName = "Kertzmann"
                        },
                        new
                        {
                            Id = new Guid("ceb50a3f-89a1-4f12-b102-21b7f3495bf2"),
                            ContactNumber = "048-354-4056",
                            CreationTime = new DateTime(2019, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "leland.reichert@conroy.com",
                            FirstName = "Christopher",
                            LastName = "Beahan"
                        },
                        new
                        {
                            Id = new Guid("39d73b1a-ecf5-44cb-b8ae-7c4627836e00"),
                            ContactNumber = "748-025-1312",
                            CreationTime = new DateTime(2019, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "donavon@kessler.name",
                            FirstName = "Hazel",
                            LastName = "Koss"
                        },
                        new
                        {
                            Id = new Guid("55b885c9-896d-4653-b236-69f716f35c12"),
                            ContactNumber = "375-125-3800 x68657",
                            CreationTime = new DateTime(2019, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "alan@gusikowski.name",
                            FirstName = "Carroll",
                            LastName = "Spinka"
                        },
                        new
                        {
                            Id = new Guid("7a9c67ff-a4a6-4023-8076-908f23b5b13d"),
                            ContactNumber = "433-827-1335 x131",
                            CreationTime = new DateTime(2019, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lori@strackenitzsche.co.uk",
                            FirstName = "Grayson",
                            LastName = "Reilly"
                        },
                        new
                        {
                            Id = new Guid("ed882c0f-c9ad-4568-b7b7-67e4bdd4fba8"),
                            ContactNumber = "463.118.7488",
                            CreationTime = new DateTime(2019, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "daphney@thompson.biz",
                            FirstName = "Dawn",
                            LastName = "Koelpin"
                        },
                        new
                        {
                            Id = new Guid("ead2e251-9927-4403-bf75-388931ddc076"),
                            ContactNumber = "1-414-315-3742",
                            CreationTime = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jazmyne@bode.ca",
                            FirstName = "Elda",
                            LastName = "Towne"
                        },
                        new
                        {
                            Id = new Guid("db1c3374-c7cf-450e-beb8-b469ac39c3e1"),
                            ContactNumber = "1-485-128-6623",
                            CreationTime = new DateTime(2019, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "octavia.connelly@hahn.co.uk",
                            FirstName = "Boyd",
                            LastName = "Mayert"
                        },
                        new
                        {
                            Id = new Guid("e18409a1-65af-45a2-9294-1764d40a879e"),
                            ContactNumber = "(865)525-8585",
                            CreationTime = new DateTime(2019, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "krystina_oberbrunner@hahnbeier.com",
                            FirstName = "Kory",
                            LastName = "Kuphal"
                        },
                        new
                        {
                            Id = new Guid("d60781f0-d107-467c-a45e-0cde8f9de567"),
                            ContactNumber = "1-125-172-5340 x873",
                            CreationTime = new DateTime(2019, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "yesenia_price@collinsschmeler.biz",
                            FirstName = "Sophie",
                            LastName = "Oberbrunner"
                        },
                        new
                        {
                            Id = new Guid("238bbd1e-8557-4a12-a98d-9b4dd69bbf27"),
                            ContactNumber = "(621)788-7675",
                            CreationTime = new DateTime(2019, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "freda.kshlerin@hayesheaney.com",
                            FirstName = "Jaeden",
                            LastName = "Hettinger"
                        },
                        new
                        {
                            Id = new Guid("d0d5fa72-20c8-448f-adf3-e19cd476e2aa"),
                            ContactNumber = "1-736-473-5677 x5843",
                            CreationTime = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "angeline_kunze@hanehaley.name",
                            FirstName = "Janet",
                            LastName = "Konopelski"
                        },
                        new
                        {
                            Id = new Guid("01a83346-affb-4773-ab2e-29f197ed88d2"),
                            ContactNumber = "411-744-8838 x8421",
                            CreationTime = new DateTime(2019, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "clay_abshire@corwin.co.uk",
                            FirstName = "Ruthie",
                            LastName = "Crona"
                        },
                        new
                        {
                            Id = new Guid("b497b0a1-8597-420b-81a4-f0b3e3bdf053"),
                            ContactNumber = "1-681-374-4821 x383",
                            CreationTime = new DateTime(2019, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "margarete@daugherty.ca",
                            FirstName = "Trystan",
                            LastName = "Gottlieb"
                        },
                        new
                        {
                            Id = new Guid("7a8ddcda-acc7-47ed-b029-250b2e95d9de"),
                            ContactNumber = "713.810.1802",
                            CreationTime = new DateTime(2019, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "taya_zulauf@weber.name",
                            FirstName = "Katlyn",
                            LastName = "Langworth"
                        },
                        new
                        {
                            Id = new Guid("9df8abe3-d38e-40d0-a1d2-ef7f18d995bc"),
                            ContactNumber = "(785)243-3636 x021",
                            CreationTime = new DateTime(2019, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "adell@huels.us",
                            FirstName = "Graciela",
                            LastName = "Senger"
                        },
                        new
                        {
                            Id = new Guid("91516c5b-6fa2-416e-a5aa-b96d3828b52f"),
                            ContactNumber = "456-222-2514 x333",
                            CreationTime = new DateTime(2019, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "roma@spinkamcglynn.us",
                            FirstName = "Allene",
                            LastName = "Considine"
                        },
                        new
                        {
                            Id = new Guid("7a60f705-a153-439c-a90a-819ec1d6de2f"),
                            ContactNumber = "(376)828-4644 x54167",
                            CreationTime = new DateTime(2019, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bertha@bruencummings.name",
                            FirstName = "Susie",
                            LastName = "Schaefer"
                        },
                        new
                        {
                            Id = new Guid("7fa5b36e-5932-415e-bafb-b5f01ee521fa"),
                            ContactNumber = "(554)876-6255 x1752",
                            CreationTime = new DateTime(2019, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "dion.jakubowski@volkman.name",
                            FirstName = "Owen",
                            LastName = "Sauer"
                        },
                        new
                        {
                            Id = new Guid("f3309f44-3454-4386-85e5-030106caf1f1"),
                            ContactNumber = "1-747-758-5003 x6347",
                            CreationTime = new DateTime(2019, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "onie.stamm@kuhnzemlak.uk",
                            FirstName = "Colin",
                            LastName = "Crona"
                        },
                        new
                        {
                            Id = new Guid("19be79b6-e7d8-4f48-9591-4f667363702e"),
                            ContactNumber = "046-785-3320 x27305",
                            CreationTime = new DateTime(2019, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mya_witting@stehr.ca",
                            FirstName = "Peggie",
                            LastName = "Legros"
                        },
                        new
                        {
                            Id = new Guid("48f51e8a-7a1a-4345-ac90-abef45d64f3e"),
                            ContactNumber = "(055)626-3844",
                            CreationTime = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "cory.pouros@armstrongfeest.info",
                            FirstName = "Golden",
                            LastName = "Conn"
                        },
                        new
                        {
                            Id = new Guid("e68693de-c6d9-4cd0-a680-2092dfde3721"),
                            ContactNumber = "788.287.2848 x26656",
                            CreationTime = new DateTime(2019, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "julien_morissette@kundekuvalis.co.uk",
                            FirstName = "Gianni",
                            LastName = "Wiza"
                        },
                        new
                        {
                            Id = new Guid("53c81c7c-96cc-4eb7-8838-88cb301449b7"),
                            ContactNumber = "287-360-1226 x642",
                            CreationTime = new DateTime(2019, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "antonette_batz@nitzschekshlerin.us",
                            FirstName = "Lambert",
                            LastName = "Lebsack"
                        },
                        new
                        {
                            Id = new Guid("d1775212-6148-4bd1-90c4-4d2e61256b8c"),
                            ContactNumber = "(606)442-7364",
                            CreationTime = new DateTime(2019, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "felicita.corkery@gulgowski.uk",
                            FirstName = "Bertha",
                            LastName = "O'Conner"
                        },
                        new
                        {
                            Id = new Guid("7d13749a-b1d7-4bb4-9394-5cf1e4bfc81d"),
                            ContactNumber = "046-344-5800",
                            CreationTime = new DateTime(2019, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "dixie@nitzschepouros.com",
                            FirstName = "Elvera",
                            LastName = "Wuckert"
                        },
                        new
                        {
                            Id = new Guid("405af629-cd56-44ca-84db-80b10cd5b630"),
                            ContactNumber = "836.626.7823 x88762",
                            CreationTime = new DateTime(2019, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "kimberly.carroll@skiles.biz",
                            FirstName = "Madison",
                            LastName = "Senger"
                        },
                        new
                        {
                            Id = new Guid("ed2ac69c-faee-4afa-b045-a6c784c113b0"),
                            ContactNumber = "(544)085-3062",
                            CreationTime = new DateTime(2019, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ines_robel@greenholtmills.co.uk",
                            FirstName = "Hulda",
                            LastName = "Hodkiewicz"
                        },
                        new
                        {
                            Id = new Guid("62e69a1e-e851-4491-9266-7075a2ff4ff3"),
                            ContactNumber = "281.248.1580 x285",
                            CreationTime = new DateTime(2019, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "giles@grady.uk",
                            FirstName = "Clara",
                            LastName = "Hickle"
                        },
                        new
                        {
                            Id = new Guid("b3a773de-ebc6-4729-84ff-b2c6e2cc7b90"),
                            ContactNumber = "1-754-128-7520",
                            CreationTime = new DateTime(2019, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "elody@johnsonskiles.us",
                            FirstName = "Kurtis",
                            LastName = "McClure"
                        },
                        new
                        {
                            Id = new Guid("6d329a58-dcb5-4a83-871a-6ea7e05191e0"),
                            ContactNumber = "623-404-1420 x780",
                            CreationTime = new DateTime(2019, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "louvenia.okuneva@price.biz",
                            FirstName = "Meredith",
                            LastName = "Ebert"
                        },
                        new
                        {
                            Id = new Guid("9020f076-a014-45e6-abb1-44dba7f047c2"),
                            ContactNumber = "(817)734-5521",
                            CreationTime = new DateTime(2019, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "audie_beier@nolanblick.uk",
                            FirstName = "Birdie",
                            LastName = "Krajcik"
                        },
                        new
                        {
                            Id = new Guid("bf392237-85e8-434f-9f75-79b569252110"),
                            ContactNumber = "045.711.2036",
                            CreationTime = new DateTime(2019, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "orlando.mccullough@okuneva.info",
                            FirstName = "Jeramy",
                            LastName = "Kovacek"
                        },
                        new
                        {
                            Id = new Guid("5ced122c-dd7d-43e3-88b8-81585c35bf12"),
                            ContactNumber = "(774)656-0725 x0676",
                            CreationTime = new DateTime(2019, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "yoshiko@goodwin.ca",
                            FirstName = "Isac",
                            LastName = "Gorczany"
                        },
                        new
                        {
                            Id = new Guid("4fd50fd2-ea42-41fa-b47c-bb76c9bc9072"),
                            ContactNumber = "224-486-1500",
                            CreationTime = new DateTime(2019, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "linda@hartmann.ca",
                            FirstName = "Tara",
                            LastName = "Kihn"
                        },
                        new
                        {
                            Id = new Guid("b40b8f78-3430-492a-8f77-c9a4259deb6e"),
                            ContactNumber = "065-613-2050 x663",
                            CreationTime = new DateTime(2019, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "darrel.casper@bernier.co.uk",
                            FirstName = "Vena",
                            LastName = "Leuschke"
                        },
                        new
                        {
                            Id = new Guid("bd97706d-75ee-44b2-a91b-005be744d73e"),
                            ContactNumber = "305-566-7530 x1456",
                            CreationTime = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "linda@cristbartell.name",
                            FirstName = "Abby",
                            LastName = "Wolf"
                        },
                        new
                        {
                            Id = new Guid("23095a85-6a48-4c1b-8710-171f2769339a"),
                            ContactNumber = "008-437-4287",
                            CreationTime = new DateTime(2019, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "gracie.sanford@hermistontrantow.us",
                            FirstName = "Gunner",
                            LastName = "Prosacco"
                        },
                        new
                        {
                            Id = new Guid("ea5c473f-056a-4892-bae8-d7c0a174fde8"),
                            ContactNumber = "467.374.5880",
                            CreationTime = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "manley@little.us",
                            FirstName = "Amelia",
                            LastName = "Hills"
                        },
                        new
                        {
                            Id = new Guid("6cc62d3b-e0af-4b83-938c-f1c9346acea9"),
                            ContactNumber = "(616)621-7671 x63275",
                            CreationTime = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "britney@mills.name",
                            FirstName = "Everardo",
                            LastName = "Rolfson"
                        },
                        new
                        {
                            Id = new Guid("f6c92de4-81a8-479b-9d1f-c6b6dfe39d96"),
                            ContactNumber = "663.205.5824 x5281",
                            CreationTime = new DateTime(2019, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mary@schummcrist.info",
                            FirstName = "Eva",
                            LastName = "Balistreri"
                        },
                        new
                        {
                            Id = new Guid("907bf85d-1e29-4236-85df-77e16835c1c8"),
                            ContactNumber = "1-881-516-2831",
                            CreationTime = new DateTime(2019, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "wilfrid_schultz@orncummerata.uk",
                            FirstName = "Everardo",
                            LastName = "Stoltenberg"
                        },
                        new
                        {
                            Id = new Guid("6ab7aa28-4590-4932-8abc-0bbb28ad250b"),
                            ContactNumber = "224-088-7011 x37332",
                            CreationTime = new DateTime(2019, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "alyce.douglas@lindgren.name",
                            FirstName = "Mozell",
                            LastName = "Becker"
                        },
                        new
                        {
                            Id = new Guid("c882305f-a826-45be-97d8-1231ae5eac73"),
                            ContactNumber = "(818)357-4666 x52747",
                            CreationTime = new DateTime(2019, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "winston@brekkedibbert.uk",
                            FirstName = "Brionna",
                            LastName = "Larson"
                        },
                        new
                        {
                            Id = new Guid("d70c967b-79fb-4874-a8c5-60fd72c5ccee"),
                            ContactNumber = "1-040-201-4730",
                            CreationTime = new DateTime(2019, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "troy.stark@bergnaum.ca",
                            FirstName = "Freddy",
                            LastName = "Quitzon"
                        },
                        new
                        {
                            Id = new Guid("428a21c4-db81-404f-a99e-645ca8716433"),
                            ContactNumber = "1-346-804-0335",
                            CreationTime = new DateTime(2019, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "santino@blick.com",
                            FirstName = "Dereck",
                            LastName = "Kris"
                        },
                        new
                        {
                            Id = new Guid("7b18e4a0-a8a9-4e1e-af2e-d6d7542e8e60"),
                            ContactNumber = "(677)580-1602",
                            CreationTime = new DateTime(2019, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "patience.nienow@cronin.co.uk",
                            FirstName = "Malcolm",
                            LastName = "Kling"
                        },
                        new
                        {
                            Id = new Guid("4ca6abe3-1199-4eca-91c7-cbc020eccd21"),
                            ContactNumber = "(052)425-6268 x10725",
                            CreationTime = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "nia_wisoky@yost.info",
                            FirstName = "Bettye",
                            LastName = "Wiza"
                        },
                        new
                        {
                            Id = new Guid("417c73f0-614b-4c4f-a804-c002dce67198"),
                            ContactNumber = "815.532.7713",
                            CreationTime = new DateTime(2019, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "maya@weimannratke.ca",
                            FirstName = "Winnifred",
                            LastName = "Feeney"
                        },
                        new
                        {
                            Id = new Guid("b55b04bd-ba49-4e01-bd7f-faf2d6639c9e"),
                            ContactNumber = "(755)671-1170 x034",
                            CreationTime = new DateTime(2019, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "cyril@cremin.info",
                            FirstName = "Rosario",
                            LastName = "Ortiz"
                        },
                        new
                        {
                            Id = new Guid("f0461a84-4a11-42c2-9a8d-8ca04ba8fb28"),
                            ContactNumber = "1-342-237-2361 x436",
                            CreationTime = new DateTime(2019, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jermain@jerde.name",
                            FirstName = "Molly",
                            LastName = "Witting"
                        },
                        new
                        {
                            Id = new Guid("85857fb7-23b5-4068-b1a9-60b9cf89c98b"),
                            ContactNumber = "853.055.3867 x11148",
                            CreationTime = new DateTime(2019, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "everette_murazik@franecki.biz",
                            FirstName = "Nannie",
                            LastName = "Cremin"
                        },
                        new
                        {
                            Id = new Guid("a8955230-4e8f-40f6-9db4-cce321f16166"),
                            ContactNumber = "(285)506-2435 x0667",
                            CreationTime = new DateTime(2019, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "dock@legros.us",
                            FirstName = "Jennifer",
                            LastName = "Kulas"
                        },
                        new
                        {
                            Id = new Guid("b3a5abe0-24aa-4eca-b620-c2b448fee435"),
                            ContactNumber = "631-868-8758 x242",
                            CreationTime = new DateTime(2019, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rubie@vandervortpadberg.co.uk",
                            FirstName = "Dan",
                            LastName = "Kuhn"
                        },
                        new
                        {
                            Id = new Guid("ac010db4-e8d4-48dc-a3ed-61f475d7159a"),
                            ContactNumber = "768-811-8230 x4185",
                            CreationTime = new DateTime(2019, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "fredy_kuhn@emard.ca",
                            FirstName = "Eino",
                            LastName = "Padberg"
                        },
                        new
                        {
                            Id = new Guid("9b613f52-d42a-4393-8811-c3e662f7bb3b"),
                            ContactNumber = "1-622-511-6143 x8666",
                            CreationTime = new DateTime(2019, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "einar_cruickshank@cummings.biz",
                            FirstName = "Ruby",
                            LastName = "Willms"
                        },
                        new
                        {
                            Id = new Guid("68d173d8-dfb6-415a-b51c-b0c766cbd4e3"),
                            ContactNumber = "544-010-0445 x0682",
                            CreationTime = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "nickolas@gutmann.co.uk",
                            FirstName = "Karen",
                            LastName = "Turcotte"
                        },
                        new
                        {
                            Id = new Guid("0979fcb8-aacd-4a92-b1d3-619f9a50d773"),
                            ContactNumber = "(723)874-4466",
                            CreationTime = new DateTime(2019, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lorna@okon.com",
                            FirstName = "Myrtice",
                            LastName = "Ziemann"
                        },
                        new
                        {
                            Id = new Guid("d83755b0-258b-4fb2-9a03-e87263bcca45"),
                            ContactNumber = "(222)716-7303",
                            CreationTime = new DateTime(2019, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "shanny@marks.info",
                            FirstName = "Rocio",
                            LastName = "Rice"
                        },
                        new
                        {
                            Id = new Guid("39647112-d919-4eff-9ef1-c790f2aab5e5"),
                            ContactNumber = "801-384-5006",
                            CreationTime = new DateTime(2019, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "laury@kertzmann.name",
                            FirstName = "Moises",
                            LastName = "DuBuque"
                        },
                        new
                        {
                            Id = new Guid("861feefd-61b1-4b0e-bb50-d9a780e68dfe"),
                            ContactNumber = "280-305-7501",
                            CreationTime = new DateTime(2019, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "leonardo@murphylakin.us",
                            FirstName = "Leanne",
                            LastName = "Keeling"
                        },
                        new
                        {
                            Id = new Guid("89e5dee5-d805-4740-8041-9d5c7ecb4120"),
                            ContactNumber = "(760)632-2453 x72034",
                            CreationTime = new DateTime(2019, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "dasia_morissette@reynolds.info",
                            FirstName = "Cooper",
                            LastName = "Corkery"
                        },
                        new
                        {
                            Id = new Guid("803cc211-4438-4ca1-b11e-cc62bcf80010"),
                            ContactNumber = "(168)604-7654",
                            CreationTime = new DateTime(2019, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "darian@bradtke.com",
                            FirstName = "Laurence",
                            LastName = "Ward"
                        },
                        new
                        {
                            Id = new Guid("38b02f39-b566-4a19-9e7a-7fb0e15d1991"),
                            ContactNumber = "(828)524-5016 x73721",
                            CreationTime = new DateTime(2019, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "kasandra_hintz@johnston.info",
                            FirstName = "Chaya",
                            LastName = "Friesen"
                        },
                        new
                        {
                            Id = new Guid("7e11c979-6b10-404d-b8f8-66089d2af99a"),
                            ContactNumber = "042-586-3018",
                            CreationTime = new DateTime(2019, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "emilie_lehner@reichel.biz",
                            FirstName = "Ubaldo",
                            LastName = "Ruecker"
                        },
                        new
                        {
                            Id = new Guid("8fb6522c-75d7-416e-97cf-e7c2c711a8f3"),
                            ContactNumber = "(814)378-4540 x723",
                            CreationTime = new DateTime(2019, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rosemary@schimmeldenesik.co.uk",
                            FirstName = "Providenci",
                            LastName = "Jacobs"
                        },
                        new
                        {
                            Id = new Guid("56a028ef-0ca7-43b3-a527-ca7f6648d70d"),
                            ContactNumber = "(822)726-6728",
                            CreationTime = new DateTime(2019, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lenore_bauch@koss.us",
                            FirstName = "Oren",
                            LastName = "Collier"
                        },
                        new
                        {
                            Id = new Guid("fec49192-58be-499a-a0db-9c85746d836b"),
                            ContactNumber = "632-087-0146 x535",
                            CreationTime = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "emily@windler.info",
                            FirstName = "Lauriane",
                            LastName = "Kuhlman"
                        },
                        new
                        {
                            Id = new Guid("6c442966-fda5-47e1-bc88-796f1e9e1e6e"),
                            ContactNumber = "1-857-473-2261 x5717",
                            CreationTime = new DateTime(2019, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "nathen@shieldsritchie.info",
                            FirstName = "Russel",
                            LastName = "McKenzie"
                        },
                        new
                        {
                            Id = new Guid("c1986b0a-12fc-41a2-ba56-7ef64ab718e2"),
                            ContactNumber = "286.638.6757 x84523",
                            CreationTime = new DateTime(2019, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "leola@dach.biz",
                            FirstName = "Pete",
                            LastName = "Fahey"
                        },
                        new
                        {
                            Id = new Guid("18fde38c-bf54-45ae-bc23-c585ed856b60"),
                            ContactNumber = "1-012-817-8665 x405",
                            CreationTime = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "guido.hayes@abshire.us",
                            FirstName = "Ora",
                            LastName = "Boyer"
                        },
                        new
                        {
                            Id = new Guid("31fcfb97-47d1-410a-b1f2-810f9829b868"),
                            ContactNumber = "618.514.4152 x36384",
                            CreationTime = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "woodrow@torp.name",
                            FirstName = "Joshuah",
                            LastName = "Kreiger"
                        },
                        new
                        {
                            Id = new Guid("23a1daf0-a056-48d9-b7ba-84ba0ac2701e"),
                            ContactNumber = "806.672.4621 x8724",
                            CreationTime = new DateTime(2019, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "alexa@kemmer.ca",
                            FirstName = "Van",
                            LastName = "Smitham"
                        },
                        new
                        {
                            Id = new Guid("409552d9-1a31-42d7-b06f-58d131cb4319"),
                            ContactNumber = "482-457-0611 x723",
                            CreationTime = new DateTime(2019, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "hershel_bailey@wilkinson.ca",
                            FirstName = "Merritt",
                            LastName = "Nikolaus"
                        },
                        new
                        {
                            Id = new Guid("54db9857-1cf8-40a5-8fd4-8c6205660a26"),
                            ContactNumber = "1-655-542-0361",
                            CreationTime = new DateTime(2019, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "juvenal_stokes@doyle.biz",
                            FirstName = "Caleigh",
                            LastName = "Olson"
                        },
                        new
                        {
                            Id = new Guid("7d49d2b6-8277-4348-866c-b15fab3f8469"),
                            ContactNumber = "1-175-366-4687 x5181",
                            CreationTime = new DateTime(2019, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "coy@torphyschneider.name",
                            FirstName = "Jameson",
                            LastName = "Gleason"
                        },
                        new
                        {
                            Id = new Guid("0d14bde0-40e2-4570-b92e-02d5baf22c0e"),
                            ContactNumber = "220-083-6310 x0468",
                            CreationTime = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "joaquin@senger.com",
                            FirstName = "Newell",
                            LastName = "Nikolaus"
                        },
                        new
                        {
                            Id = new Guid("29de96d1-2c26-4f66-a97e-6735cadcb7ca"),
                            ContactNumber = "876.117.5384 x230",
                            CreationTime = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "nelson_haley@keeling.com",
                            FirstName = "Travon",
                            LastName = "Turner"
                        },
                        new
                        {
                            Id = new Guid("7f84a054-6318-4e3b-8473-7c6468d55a78"),
                            ContactNumber = "1-243-406-3636 x0111",
                            CreationTime = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "keely_olson@watsica.ca",
                            FirstName = "Sofia",
                            LastName = "O'Hara"
                        },
                        new
                        {
                            Id = new Guid("e3918dd6-968a-4160-af95-6526c74bc4b8"),
                            ContactNumber = "1-168-443-0108 x641",
                            CreationTime = new DateTime(2019, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "dan@langworth.us",
                            FirstName = "Annalise",
                            LastName = "Rutherford"
                        },
                        new
                        {
                            Id = new Guid("c0a5db37-f954-46de-8178-546f361a65f6"),
                            ContactNumber = "167-847-6163 x587",
                            CreationTime = new DateTime(2019, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "guiseppe@ullrich.name",
                            FirstName = "Marshall",
                            LastName = "Macejkovic"
                        },
                        new
                        {
                            Id = new Guid("a74c4210-3618-41f9-8a76-e4bf7e4af775"),
                            ContactNumber = "(703)377-8560",
                            CreationTime = new DateTime(2019, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "patience_grimes@marvinwilliamson.com",
                            FirstName = "Alanna",
                            LastName = "Connelly"
                        },
                        new
                        {
                            Id = new Guid("c3be23b4-f787-419d-9ecf-f702f391d9d6"),
                            ContactNumber = "271-416-2006",
                            CreationTime = new DateTime(2019, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "eileen_stracke@langworth.name",
                            FirstName = "Isai",
                            LastName = "Shanahan"
                        },
                        new
                        {
                            Id = new Guid("cc2739a3-3e3e-469d-8ca0-a31c2dd877dc"),
                            ContactNumber = "1-480-405-2275 x2042",
                            CreationTime = new DateTime(2019, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ruby@beckerpouros.ca",
                            FirstName = "Constance",
                            LastName = "Barrows"
                        });
                });

            modelBuilder.Entity("Rental.DataAccess.Entities.GameRental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BoardGameId");

                    b.Property<float>("ChargedDeposit");

                    b.Property<Guid>("ClientId");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 8, 10, 8, 12, 45, 156, DateTimeKind.Utc).AddTicks(3919));

                    b.Property<float>("PaidMoney");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("BoardGameId");

                    b.HasIndex("ClientId");

                    b.ToTable("GameRentals");
                });

            modelBuilder.Entity("Rental.DataAccess.Entities.GameRental", b =>
                {
                    b.HasOne("Rental.DataAccess.Entities.BoardGame", "BoardGame")
                        .WithMany("GameRentals")
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rental.DataAccess.Entities.Client", "Client")
                        .WithMany("GameRentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
