// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Rental.DataAccess.Context;

namespace Rental.DataAccess.Migrations
{
    [DbContext(typeof(RentalContext))]
    internal class RentalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("r")
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6");

            modelBuilder.Entity("Rental.DataAccess.Entities.BoardGame", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<DateTime>("CreationTime")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(new DateTime(2019, 8, 8, 19, 58, 48, 823, DateTimeKind.Utc).AddTicks(6060));

                b.Property<string>("Name");

                b.Property<float>("Price");

                b.HasKey("Id");

                b.ToTable("BoardGames");
            });

            modelBuilder.Entity("Rental.DataAccess.Entities.Client", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("ContactNumber");

                b.Property<DateTime>("CreationTime")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(new DateTime(2019, 8, 8, 19, 58, 48, 826, DateTimeKind.Utc).AddTicks(4660));

                b.Property<string>("EmailAddress");

                b.Property<string>("FirstName");

                b.Property<string>("LastName");

                b.HasKey("Id");

                b.ToTable("Clients");

                b.HasData(
                    new
                    {
                        Id = new Guid("52543234-6e9b-4483-840c-79750a27c8cb"),
                        ContactNumber = "138.886.7742 x681",
                        CreationTime = new DateTime(2019, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "isobel@wittingconnelly.info",
                        FirstName = "Heidi",
                        LastName = "Maggio"
                    },
                    new
                    {
                        Id = new Guid("28286518-2c05-48de-8c29-f894f079a44b"),
                        ContactNumber = "451.251.0421 x53708",
                        CreationTime = new DateTime(2019, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "finn.mcglynn@huel.info",
                        FirstName = "Lawrence",
                        LastName = "Doyle"
                    },
                    new
                    {
                        Id = new Guid("b529c3d7-988c-4227-a0cb-d8b31cfc9c2d"),
                        ContactNumber = "1-830-483-1737 x50670",
                        CreationTime = new DateTime(2019, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "lexus.schultz@jerdemonahan.co.uk",
                        FirstName = "Marion",
                        LastName = "Gaylord"
                    },
                    new
                    {
                        Id = new Guid("b350a987-7d15-4b1a-9233-febb879cb1c8"),
                        ContactNumber = "251-725-3200",
                        CreationTime = new DateTime(2019, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "kolby@altenwerth.ca",
                        FirstName = "Ozella",
                        LastName = "Pacocha"
                    },
                    new
                    {
                        Id = new Guid("f0b3349a-1319-4528-95ec-fecca0e0076e"),
                        ContactNumber = "1-813-414-7643",
                        CreationTime = new DateTime(2019, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "elwyn@wilkinson.biz",
                        FirstName = "Caesar",
                        LastName = "Powlowski"
                    },
                    new
                    {
                        Id = new Guid("5e0f897c-6ad9-4c40-a62d-c11a4c35414b"),
                        ContactNumber = "(636)850-6772",
                        CreationTime = new DateTime(2019, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "skylar@little.com",
                        FirstName = "Lilla",
                        LastName = "Kuhic"
                    },
                    new
                    {
                        Id = new Guid("9ce68399-3eed-47a6-9518-de0493c02363"),
                        ContactNumber = "765-666-8667 x0485",
                        CreationTime = new DateTime(2019, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jade.hermann@sanfordcartwright.info",
                        FirstName = "Cyrus",
                        LastName = "Robel"
                    },
                    new
                    {
                        Id = new Guid("469c2dab-8763-4b64-b9ea-73e25257e8ea"),
                        ContactNumber = "232-278-3806",
                        CreationTime = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "alexanne@bergnaum.us",
                        FirstName = "Angelita",
                        LastName = "Weissnat"
                    },
                    new
                    {
                        Id = new Guid("27b2a59f-e69c-4152-86ef-e1edde1b4a42"),
                        ContactNumber = "712.405.7784 x8564",
                        CreationTime = new DateTime(2019, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "ervin@hodkiewicz.ca",
                        FirstName = "Tyrese",
                        LastName = "Walsh"
                    },
                    new
                    {
                        Id = new Guid("1be61906-1988-4f49-bb5e-1170b3ed3b10"),
                        ContactNumber = "136.210.7711 x41162",
                        CreationTime = new DateTime(2019, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "colton@yostkuphal.biz",
                        FirstName = "Jordan",
                        LastName = "Weber"
                    },
                    new
                    {
                        Id = new Guid("81f2e78c-f17b-42c8-abbd-f75dc25e1279"),
                        ContactNumber = "670-800-1212",
                        CreationTime = new DateTime(2019, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "malcolm@kunde.biz",
                        FirstName = "Nicola",
                        LastName = "Hayes"
                    },
                    new
                    {
                        Id = new Guid("bfb29133-9ac4-401d-9f63-d7ce0ad9039a"),
                        ContactNumber = "1-011-816-6043 x240",
                        CreationTime = new DateTime(2019, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "lilla.wyman@schroeder.com",
                        FirstName = "Bethany",
                        LastName = "Kuphal"
                    },
                    new
                    {
                        Id = new Guid("0c37e43a-2038-4e03-a037-b294bb870676"),
                        ContactNumber = "(526)807-5271 x460",
                        CreationTime = new DateTime(2019, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "gabriella.connelly@roberts.ca",
                        FirstName = "Adele",
                        LastName = "Weissnat"
                    },
                    new
                    {
                        Id = new Guid("7a0416f1-5c8d-4e82-a8aa-614e065b2d55"),
                        ContactNumber = "(872)357-1145",
                        CreationTime = new DateTime(2019, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "willis@kovacek.biz",
                        FirstName = "Franz",
                        LastName = "Swift"
                    },
                    new
                    {
                        Id = new Guid("541ab43f-df6d-462c-ab93-6bb873151df8"),
                        ContactNumber = "158.036.7328",
                        CreationTime = new DateTime(2019, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "zander_sipes@brekke.info",
                        FirstName = "Cole",
                        LastName = "Grant"
                    },
                    new
                    {
                        Id = new Guid("747c0d00-b7b2-49c0-8f7e-584737f62e4a"),
                        ContactNumber = "(452)830-2025",
                        CreationTime = new DateTime(2019, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "adele@ohara.info",
                        FirstName = "Daphney",
                        LastName = "Hand"
                    },
                    new
                    {
                        Id = new Guid("d3bc561b-47e3-4adf-8243-abdd34a0bfbc"),
                        ContactNumber = "827-541-3363 x300",
                        CreationTime = new DateTime(2019, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "arvid.runolfsdottir@jacobiryan.com",
                        FirstName = "Lorenza",
                        LastName = "Reynolds"
                    },
                    new
                    {
                        Id = new Guid("259d2801-f069-4c9b-9bad-44af7b5533a3"),
                        ContactNumber = "681-000-3248",
                        CreationTime = new DateTime(2019, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "emie@padberg.biz",
                        FirstName = "Cassandre",
                        LastName = "Pfannerstill"
                    },
                    new
                    {
                        Id = new Guid("d0e68616-4363-4988-80b8-7916b43c1a52"),
                        ContactNumber = "(228)756-0328 x26477",
                        CreationTime = new DateTime(2019, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "alfredo.haag@armstrong.com",
                        FirstName = "Tad",
                        LastName = "Herzog"
                    },
                    new
                    {
                        Id = new Guid("a43fb9c8-a152-4fb3-8ff1-e1292bf6faa8"),
                        ContactNumber = "081.127.7648 x242",
                        CreationTime = new DateTime(2019, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "ahmad_lesch@mannsatterfield.info",
                        FirstName = "Keanu",
                        LastName = "Runte"
                    },
                    new
                    {
                        Id = new Guid("2a272a52-4157-4023-a280-67d8c45ff031"),
                        ContactNumber = "255.716.7271",
                        CreationTime = new DateTime(2019, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "gwen@spencer.name",
                        FirstName = "Queenie",
                        LastName = "VonRueden"
                    },
                    new
                    {
                        Id = new Guid("214be500-8b1a-4764-8ad3-6d36d21caf28"),
                        ContactNumber = "568-868-1048 x862",
                        CreationTime = new DateTime(2019, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "adrain@nicolas.ca",
                        FirstName = "Mayra",
                        LastName = "Buckridge"
                    },
                    new
                    {
                        Id = new Guid("19d5381e-41a8-4e30-a821-d74914c02278"),
                        ContactNumber = "518-586-5506",
                        CreationTime = new DateTime(2019, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "edmond@heidenreichmueller.name",
                        FirstName = "Peggie",
                        LastName = "Boyer"
                    },
                    new
                    {
                        Id = new Guid("45846dfb-c090-4743-bf41-c62b93ada894"),
                        ContactNumber = "227-363-0837 x6454",
                        CreationTime = new DateTime(2019, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "domingo_smitham@deckowharber.name",
                        FirstName = "Roger",
                        LastName = "Batz"
                    },
                    new
                    {
                        Id = new Guid("670913cd-7c11-4344-8089-57632a13947d"),
                        ContactNumber = "775.402.1417 x67712",
                        CreationTime = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "maximilian.schaefer@durganschamberger.info",
                        FirstName = "Gerhard",
                        LastName = "Volkman"
                    },
                    new
                    {
                        Id = new Guid("988f83e7-f1d8-4f77-b236-3159d49d557a"),
                        ContactNumber = "047-238-8375 x44354",
                        CreationTime = new DateTime(2019, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jalon@yost.biz",
                        FirstName = "Mavis",
                        LastName = "Block"
                    },
                    new
                    {
                        Id = new Guid("a9e828c4-bea0-4337-8a7c-8b7650dc530f"),
                        ContactNumber = "754-600-8311 x6674",
                        CreationTime = new DateTime(2019, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "vergie.hermiston@koepp.com",
                        FirstName = "Bettye",
                        LastName = "Glover"
                    },
                    new
                    {
                        Id = new Guid("aefff944-5970-4f3e-b66b-2e7fd7adf1c8"),
                        ContactNumber = "1-065-733-5642",
                        CreationTime = new DateTime(2019, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "malvina@leffler.com",
                        FirstName = "Renee",
                        LastName = "Dickinson"
                    },
                    new
                    {
                        Id = new Guid("d861a85b-2e78-4833-bb0f-f8c06b14425a"),
                        ContactNumber = "1-521-452-3730",
                        CreationTime = new DateTime(2019, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "mireille@russelbalistreri.com",
                        FirstName = "Gerard",
                        LastName = "Spencer"
                    },
                    new
                    {
                        Id = new Guid("17931351-4ec0-4e0b-9fd7-26451491f116"),
                        ContactNumber = "301.855.6518 x0478",
                        CreationTime = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "mathilde_marvin@cummings.name",
                        FirstName = "Nicola",
                        LastName = "Herman"
                    },
                    new
                    {
                        Id = new Guid("661c0e1f-9c47-4878-914a-04e50a1a440b"),
                        ContactNumber = "(850)843-3754 x243",
                        CreationTime = new DateTime(2019, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "rusty_orn@treutel.ca",
                        FirstName = "Orpha",
                        LastName = "Friesen"
                    },
                    new
                    {
                        Id = new Guid("b3de9110-d2ab-4fec-b6bb-0ac6458be18d"),
                        ContactNumber = "1-025-515-3284 x5855",
                        CreationTime = new DateTime(2019, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "kadin_padberg@lang.com",
                        FirstName = "Katelin",
                        LastName = "Ritchie"
                    },
                    new
                    {
                        Id = new Guid("1c593cc7-5edd-4c29-9d93-4e986635cd1e"),
                        ContactNumber = "1-146-788-3738",
                        CreationTime = new DateTime(2019, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "olen@parisian.name",
                        FirstName = "Esperanza",
                        LastName = "Zieme"
                    },
                    new
                    {
                        Id = new Guid("b8deabc1-b559-4a59-92f3-0c0d0c8b9c55"),
                        ContactNumber = "1-730-434-7221 x78528",
                        CreationTime = new DateTime(2019, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "modesta@wolfkuphal.us",
                        FirstName = "Laura",
                        LastName = "VonRueden"
                    },
                    new
                    {
                        Id = new Guid("6d2f1b10-7427-4660-a6f1-44a546f6cc3a"),
                        ContactNumber = "1-460-824-5530 x4731",
                        CreationTime = new DateTime(2019, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "freda.barton@feilauer.com",
                        FirstName = "Austyn",
                        LastName = "Fahey"
                    },
                    new
                    {
                        Id = new Guid("6ca58327-56a7-4e17-b980-a829732efdd4"),
                        ContactNumber = "(724)535-7120 x5470",
                        CreationTime = new DateTime(2019, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jayme.mayer@rowedare.biz",
                        FirstName = "Carter",
                        LastName = "Lockman"
                    },
                    new
                    {
                        Id = new Guid("25df9c1c-84af-40f8-a0be-98b561f365d0"),
                        ContactNumber = "323-862-5423 x1188",
                        CreationTime = new DateTime(2019, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "mark@cummerataconnelly.name",
                        FirstName = "Katelynn",
                        LastName = "Ullrich"
                    },
                    new
                    {
                        Id = new Guid("dcdc5c65-ef19-4209-88ac-a45cf17a12af"),
                        ContactNumber = "1-866-557-4065 x00331",
                        CreationTime = new DateTime(2019, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "mittie_brakus@padbergmccullough.us",
                        FirstName = "Ramon",
                        LastName = "Glover"
                    },
                    new
                    {
                        Id = new Guid("f2a8485c-b8e8-4f67-b02f-46c378b82173"),
                        ContactNumber = "045.387.1242",
                        CreationTime = new DateTime(2019, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "maurine_ondricka@harris.name",
                        FirstName = "Dorcas",
                        LastName = "McCullough"
                    },
                    new
                    {
                        Id = new Guid("7fdb4aa0-7e49-4ff9-afba-b9743dcd921f"),
                        ContactNumber = "1-453-866-2234",
                        CreationTime = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jaime@zieme.biz",
                        FirstName = "Victor",
                        LastName = "Wolf"
                    },
                    new
                    {
                        Id = new Guid("c8522e31-b936-4604-87bb-e1c504a4eb2e"),
                        ContactNumber = "1-785-003-6317",
                        CreationTime = new DateTime(2019, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "lilyan@rice.name",
                        FirstName = "Cordie",
                        LastName = "Von"
                    },
                    new
                    {
                        Id = new Guid("ad055caf-4ca8-47d7-b7bf-213e3db14e8b"),
                        ContactNumber = "(301)745-4877",
                        CreationTime = new DateTime(2019, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "seamus@baumbach.ca",
                        FirstName = "Yvette",
                        LastName = "Berge"
                    },
                    new
                    {
                        Id = new Guid("93a1fe98-563c-4abb-a9d7-bf87675886f1"),
                        ContactNumber = "1-288-141-3288 x53514",
                        CreationTime = new DateTime(2019, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "leo@bergstrom.uk",
                        FirstName = "Anabel",
                        LastName = "Howell"
                    },
                    new
                    {
                        Id = new Guid("fecb7ea8-a538-42c8-b945-014623ab70f9"),
                        ContactNumber = "1-184-521-4751 x731",
                        CreationTime = new DateTime(2019, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "eliseo@gerhold.name",
                        FirstName = "Jedidiah",
                        LastName = "Welch"
                    },
                    new
                    {
                        Id = new Guid("1c3ade05-30bc-4ccc-87c6-dff4834c0012"),
                        ContactNumber = "(254)684-8037 x0305",
                        CreationTime = new DateTime(2019, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "richard_rutherford@quigleyrosenbaum.uk",
                        FirstName = "Reinhold",
                        LastName = "Effertz"
                    },
                    new
                    {
                        Id = new Guid("99cd8f2b-2423-4349-bf56-62f60028b278"),
                        ContactNumber = "476.024.1236 x70428",
                        CreationTime = new DateTime(2019, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "kim_baumbach@rippinbahringer.biz",
                        FirstName = "Eldora",
                        LastName = "Considine"
                    },
                    new
                    {
                        Id = new Guid("58415266-7c92-4ec4-bc48-ae24ee42ebd4"),
                        ContactNumber = "(124)873-3736",
                        CreationTime = new DateTime(2019, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "theresia@gleason.co.uk",
                        FirstName = "Loraine",
                        LastName = "Kassulke"
                    },
                    new
                    {
                        Id = new Guid("458a74e7-7620-4d81-8460-708027ae04c4"),
                        ContactNumber = "634-571-6272 x40168",
                        CreationTime = new DateTime(2019, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "reynold@kuhn.biz",
                        FirstName = "Leila",
                        LastName = "Trantow"
                    },
                    new
                    {
                        Id = new Guid("58c1855b-9dc4-492b-90a1-fafd62a45662"),
                        ContactNumber = "(554)636-3776",
                        CreationTime = new DateTime(2019, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "melyna_pfannerstill@donnelly.ca",
                        FirstName = "Mose",
                        LastName = "Volkman"
                    },
                    new
                    {
                        Id = new Guid("17efd7fe-c088-4651-b7d6-792361cc36ea"),
                        ContactNumber = "1-218-021-0206",
                        CreationTime = new DateTime(2019, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "emelia.lehner@kozey.ca",
                        FirstName = "Robbie",
                        LastName = "Olson"
                    },
                    new
                    {
                        Id = new Guid("d09c670d-dd40-44fd-b73c-75a2d9c7aa86"),
                        ContactNumber = "1-015-016-5311",
                        CreationTime = new DateTime(2019, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "larissa@jacobsonheaney.info",
                        FirstName = "Bethel",
                        LastName = "Doyle"
                    },
                    new
                    {
                        Id = new Guid("8b0b174b-d37a-4f95-b0d0-b58fd2501d9a"),
                        ContactNumber = "1-645-113-4105",
                        CreationTime = new DateTime(2019, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "amalia@kling.co.uk",
                        FirstName = "Emilie",
                        LastName = "Koelpin"
                    },
                    new
                    {
                        Id = new Guid("8a4aa94c-459c-493a-9c31-fe2984525330"),
                        ContactNumber = "(348)844-6517",
                        CreationTime = new DateTime(2019, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "annie.schowalter@sengerhuel.name",
                        FirstName = "Flavio",
                        LastName = "Zulauf"
                    },
                    new
                    {
                        Id = new Guid("ac6ffe40-b7fd-4005-9673-45998ac4901b"),
                        ContactNumber = "446-803-1612 x4238",
                        CreationTime = new DateTime(2019, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "kallie@muller.name",
                        FirstName = "Janelle",
                        LastName = "Pfannerstill"
                    },
                    new
                    {
                        Id = new Guid("7066c996-9eee-42da-bbeb-057891130673"),
                        ContactNumber = "088.887.1724 x78184",
                        CreationTime = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "lacey@windler.info",
                        FirstName = "Ashtyn",
                        LastName = "Gibson"
                    },
                    new
                    {
                        Id = new Guid("6585c2fb-5a7c-4a24-a9af-831224a12391"),
                        ContactNumber = "262-785-3267",
                        CreationTime = new DateTime(2019, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "isobel@schmeler.co.uk",
                        FirstName = "Maxwell",
                        LastName = "Swaniawski"
                    },
                    new
                    {
                        Id = new Guid("2c76fc93-394d-4748-bf1f-ac8d5fde02ba"),
                        ContactNumber = "(022)614-0116 x73206",
                        CreationTime = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "carroll_bechtelar@schuster.biz",
                        FirstName = "King",
                        LastName = "Abshire"
                    },
                    new
                    {
                        Id = new Guid("5239a3ef-5db7-4139-846d-320912fd5221"),
                        ContactNumber = "1-630-545-6770",
                        CreationTime = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "tanner.hauck@little.name",
                        FirstName = "Jacinthe",
                        LastName = "Bergstrom"
                    },
                    new
                    {
                        Id = new Guid("a3f27cc6-59e2-4c79-8b11-67c44a56f831"),
                        ContactNumber = "311-246-0647 x677",
                        CreationTime = new DateTime(2019, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "arvid.funk@mohr.us",
                        FirstName = "Jonathon",
                        LastName = "Stehr"
                    },
                    new
                    {
                        Id = new Guid("955033b2-1d38-4e33-9a24-e528631fbe93"),
                        ContactNumber = "(663)201-4442",
                        CreationTime = new DateTime(2019, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "ted@dubuquebotsford.co.uk",
                        FirstName = "Mireya",
                        LastName = "Rempel"
                    },
                    new
                    {
                        Id = new Guid("5800e242-3421-4df7-bf2d-630e72b96a38"),
                        ContactNumber = "1-012-424-7278 x316",
                        CreationTime = new DateTime(2019, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "summer@schroedergerhold.info",
                        FirstName = "Mustafa",
                        LastName = "Boyle"
                    },
                    new
                    {
                        Id = new Guid("d9b04964-6755-4d68-b40c-f788b4a4a629"),
                        ContactNumber = "134.518.0046",
                        CreationTime = new DateTime(2019, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "cyril@bayerjones.com",
                        FirstName = "Kristopher",
                        LastName = "Herman"
                    },
                    new
                    {
                        Id = new Guid("557fcd48-1605-458d-8dfe-c32fc4352df4"),
                        ContactNumber = "(765)013-4552",
                        CreationTime = new DateTime(2019, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "trenton_corwin@bechtelar.ca",
                        FirstName = "Clint",
                        LastName = "Schroeder"
                    },
                    new
                    {
                        Id = new Guid("68a2ab88-713b-4e8d-bd65-d5357a95e3fc"),
                        ContactNumber = "(635)846-7150",
                        CreationTime = new DateTime(2019, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "emil.prohaska@hagenesjacobson.us",
                        FirstName = "Elbert",
                        LastName = "Sporer"
                    },
                    new
                    {
                        Id = new Guid("821b0c0f-6afc-4e44-93e0-b6344708dfe8"),
                        ContactNumber = "767.508.8415",
                        CreationTime = new DateTime(2019, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "helene_windler@johns.name",
                        FirstName = "Louie",
                        LastName = "Jacobi"
                    },
                    new
                    {
                        Id = new Guid("d1306e26-0100-451e-b3c6-464797f1a627"),
                        ContactNumber = "1-568-158-4553 x547",
                        CreationTime = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "lavina_hayes@rutherfordstroman.ca",
                        FirstName = "Pink",
                        LastName = "Reinger"
                    },
                    new
                    {
                        Id = new Guid("9576bc73-27d3-492c-9b58-17b41b87da42"),
                        ContactNumber = "(886)182-3767 x107",
                        CreationTime = new DateTime(2019, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "hanna@kiehn.com",
                        FirstName = "Ida",
                        LastName = "Kovacek"
                    },
                    new
                    {
                        Id = new Guid("ca9ef73b-d0a6-40ac-bab5-a79a0db433f2"),
                        ContactNumber = "1-064-740-7812 x4262",
                        CreationTime = new DateTime(2019, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "markus@wolf.info",
                        FirstName = "Sally",
                        LastName = "Wolf"
                    },
                    new
                    {
                        Id = new Guid("408c8550-f16c-48d3-b76e-6a967c52b4fc"),
                        ContactNumber = "088.735.7258 x164",
                        CreationTime = new DateTime(2019, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jamey@schulist.name",
                        FirstName = "Yasmine",
                        LastName = "Schmidt"
                    },
                    new
                    {
                        Id = new Guid("281ea0d8-9943-4dfd-b019-49e311f10e4f"),
                        ContactNumber = "1-560-222-0162",
                        CreationTime = new DateTime(2019, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "judge@lang.us",
                        FirstName = "Nicole",
                        LastName = "Herzog"
                    },
                    new
                    {
                        Id = new Guid("3833afb8-16bb-4cdc-9dad-26abc15a2e62"),
                        ContactNumber = "(354)737-0080 x77663",
                        CreationTime = new DateTime(2019, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "emmanuel@mayertwisoky.ca",
                        FirstName = "Gail",
                        LastName = "Bartell"
                    },
                    new
                    {
                        Id = new Guid("c0153681-9312-4f06-ae97-f33d9cca21af"),
                        ContactNumber = "(375)353-5464 x601",
                        CreationTime = new DateTime(2019, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "tracy@crooksbatz.com",
                        FirstName = "Michele",
                        LastName = "Homenick"
                    },
                    new
                    {
                        Id = new Guid("f2a5c33c-1c60-4047-8e56-1ee2c50b12e1"),
                        ContactNumber = "(711)118-7026",
                        CreationTime = new DateTime(2019, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "angus@lefflergusikowski.biz",
                        FirstName = "Maximilian",
                        LastName = "Hegmann"
                    },
                    new
                    {
                        Id = new Guid("2f60767a-7810-43cd-9b3b-41226e9bafeb"),
                        ContactNumber = "301-828-0317 x446",
                        CreationTime = new DateTime(2019, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "barrett@jakubowski.us",
                        FirstName = "Haven",
                        LastName = "McGlynn"
                    },
                    new
                    {
                        Id = new Guid("9a5bd8ce-755c-444c-905f-78339887a8a8"),
                        ContactNumber = "(107)173-0355 x2016",
                        CreationTime = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "rubie@bins.ca",
                        FirstName = "Lulu",
                        LastName = "Rohan"
                    },
                    new
                    {
                        Id = new Guid("568051a2-245e-437e-b96f-957fdb66c5bd"),
                        ContactNumber = "583.585.8275",
                        CreationTime = new DateTime(2019, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "alejandra@lind.co.uk",
                        FirstName = "Destin",
                        LastName = "Schmidt"
                    },
                    new
                    {
                        Id = new Guid("e96d977c-e35f-402f-9eab-540874e2e58d"),
                        ContactNumber = "(731)822-3110 x13381",
                        CreationTime = new DateTime(2019, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jewell@dubuque.us",
                        FirstName = "Arch",
                        LastName = "Howe"
                    },
                    new
                    {
                        Id = new Guid("37ae5030-7022-4594-b233-29476d69744c"),
                        ContactNumber = "522.474.4783 x1732",
                        CreationTime = new DateTime(2019, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "damien_considine@klein.co.uk",
                        FirstName = "Ivory",
                        LastName = "Jewess"
                    },
                    new
                    {
                        Id = new Guid("9509bb0a-b1ec-475e-9bb1-87f4205f14b5"),
                        ContactNumber = "1-174-248-6158 x0624",
                        CreationTime = new DateTime(2019, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "juvenal.leannon@hoeger.ca",
                        FirstName = "Emmett",
                        LastName = "Mertz"
                    },
                    new
                    {
                        Id = new Guid("0db23b44-b3e1-4b6a-b749-15b6d744be4d"),
                        ContactNumber = "(168)682-8713 x63571",
                        CreationTime = new DateTime(2019, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "dorothea@padbergdoyle.co.uk",
                        FirstName = "Katrina",
                        LastName = "Nienow"
                    },
                    new
                    {
                        Id = new Guid("ec3bd9e1-edfc-4eac-994a-20104659a3b4"),
                        ContactNumber = "(414)215-5273 x22636",
                        CreationTime = new DateTime(2019, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "alek_crooks@waelchi.info",
                        FirstName = "Retta",
                        LastName = "Daniel"
                    },
                    new
                    {
                        Id = new Guid("5452af5f-2764-435f-8750-22cf68a34c54"),
                        ContactNumber = "(787)373-5026",
                        CreationTime = new DateTime(2019, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "obie_leffler@hermann.ca",
                        FirstName = "Lulu",
                        LastName = "White"
                    },
                    new
                    {
                        Id = new Guid("5d58ad55-44f7-4891-99ab-b5830b5a6180"),
                        ContactNumber = "881-150-8237 x28763",
                        CreationTime = new DateTime(2019, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jessie@osinski.name",
                        FirstName = "Sven",
                        LastName = "Heidenreich"
                    },
                    new
                    {
                        Id = new Guid("d41aea47-de00-4849-a670-de07b251dac9"),
                        ContactNumber = "535-640-0888",
                        CreationTime = new DateTime(2019, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "devon_pouros@cronaullrich.us",
                        FirstName = "Tyrel",
                        LastName = "Gerlach"
                    },
                    new
                    {
                        Id = new Guid("9f8d9872-dbc6-493c-88ee-c5502508f30c"),
                        ContactNumber = "1-608-075-2650 x0880",
                        CreationTime = new DateTime(2019, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "garrison_turcotte@feest.biz",
                        FirstName = "Trey",
                        LastName = "Kuhlman"
                    },
                    new
                    {
                        Id = new Guid("a359a7bd-982d-4f08-8b08-21b20073eed5"),
                        ContactNumber = "214.240.6482 x5664",
                        CreationTime = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "darrell.turcotte@hegmann.name",
                        FirstName = "Joshuah",
                        LastName = "Dickens"
                    },
                    new
                    {
                        Id = new Guid("e51cb4f4-5ce7-4a82-aba7-acbcdeb52072"),
                        ContactNumber = "(126)733-7031 x134",
                        CreationTime = new DateTime(2019, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "bud@botsfordheaney.biz",
                        FirstName = "Osvaldo",
                        LastName = "Haley"
                    },
                    new
                    {
                        Id = new Guid("f6c9fb9e-935b-4af4-b1cc-c6eae9843681"),
                        ContactNumber = "(364)757-8516",
                        CreationTime = new DateTime(2019, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "archibald_langworth@buckridge.name",
                        FirstName = "Shanon",
                        LastName = "Dooley"
                    },
                    new
                    {
                        Id = new Guid("5e1b746a-f521-4c70-9dac-b37d0d8fad75"),
                        ContactNumber = "(083)813-5503 x2878",
                        CreationTime = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "katarina@wyman.name",
                        FirstName = "Marlon",
                        LastName = "Conroy"
                    },
                    new
                    {
                        Id = new Guid("45dc60d3-090e-47ab-9af1-ee5020008ccf"),
                        ContactNumber = "155-834-8416 x653",
                        CreationTime = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "loy_barton@oharalubowitz.info",
                        FirstName = "Jewel",
                        LastName = "Heller"
                    },
                    new
                    {
                        Id = new Guid("79c1d465-f19c-41b1-b086-be53bb4fd402"),
                        ContactNumber = "734-853-7458 x65751",
                        CreationTime = new DateTime(2019, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "hortense_sauer@emard.co.uk",
                        FirstName = "Sven",
                        LastName = "Pollich"
                    },
                    new
                    {
                        Id = new Guid("70c691e6-8037-48b3-b0cb-7a51749b3da3"),
                        ContactNumber = "(627)752-8610 x007",
                        CreationTime = new DateTime(2019, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "trudie.weber@wunschberge.biz",
                        FirstName = "Asa",
                        LastName = "Heathcote"
                    },
                    new
                    {
                        Id = new Guid("7f2b9658-82b5-4fed-8431-2b599ba1e217"),
                        ContactNumber = "(101)551-2351",
                        CreationTime = new DateTime(2019, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "julien_smith@kessler.co.uk",
                        FirstName = "Imani",
                        LastName = "Kris"
                    },
                    new
                    {
                        Id = new Guid("12ad3d27-4256-416d-a2e5-366afa493632"),
                        ContactNumber = "370.186.5026 x277",
                        CreationTime = new DateTime(2019, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "kiel.harvey@wunsch.ca",
                        FirstName = "Jaeden",
                        LastName = "Cartwright"
                    },
                    new
                    {
                        Id = new Guid("133f64bb-c5cf-4f5b-9e09-6477679005d8"),
                        ContactNumber = "340-143-5834",
                        CreationTime = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "christop.kilback@howeparisian.us",
                        FirstName = "Kamryn",
                        LastName = "Reilly"
                    },
                    new
                    {
                        Id = new Guid("b904cac1-8e78-443d-9ea7-146836b0ad4e"),
                        ContactNumber = "(671)622-8438 x710",
                        CreationTime = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "izabella_hilpert@stoltenbergbruen.us",
                        FirstName = "Donnell",
                        LastName = "Homenick"
                    },
                    new
                    {
                        Id = new Guid("6cbdc0ed-7525-414f-ac56-cb8d1e2bc980"),
                        ContactNumber = "(307)450-3234 x65842",
                        CreationTime = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "maxwell@zulaufkuvalis.name",
                        FirstName = "Henry",
                        LastName = "Hackett"
                    },
                    new
                    {
                        Id = new Guid("78d43d08-f264-468f-b742-df2f1bac42d8"),
                        ContactNumber = "1-162-632-1252 x2134",
                        CreationTime = new DateTime(2019, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "duncan_leffler@kutch.biz",
                        FirstName = "Alexane",
                        LastName = "Adams"
                    },
                    new
                    {
                        Id = new Guid("f5d2b88b-2b7d-4a1d-818c-48bb4dbd3004"),
                        ContactNumber = "1-363-783-0127 x6570",
                        CreationTime = new DateTime(2019, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "favian@osinski.co.uk",
                        FirstName = "Saul",
                        LastName = "Hagenes"
                    },
                    new
                    {
                        Id = new Guid("1533f374-7325-4ed5-97d4-0ee81852b743"),
                        ContactNumber = "674-245-3833 x5738",
                        CreationTime = new DateTime(2019, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "flavio_braun@cole.ca",
                        FirstName = "Maxine",
                        LastName = "Frami"
                    });
            });

            modelBuilder.Entity("Rental.DataAccess.Entities.GameRental", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<int>("BoardGameId");

                b.Property<Guid?>("BoardGameId1");

                b.Property<float>("ChargedDeposit");

                b.Property<int>("ClientId");

                b.Property<Guid?>("ClientId1");

                b.Property<DateTime>("CreationTime")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(new DateTime(2019, 8, 8, 19, 58, 48, 826, DateTimeKind.Utc).AddTicks(2930));

                b.Property<float>("PaidMoney");

                b.Property<int>("Status");

                b.HasKey("Id");

                b.HasIndex("BoardGameId1");

                b.HasIndex("ClientId1");

                b.ToTable("GameRentals");
            });

            modelBuilder.Entity("Rental.DataAccess.Entities.GameRental", b =>
            {
                b.HasOne("Rental.DataAccess.Entities.BoardGame", "BoardGame")
                    .WithMany("GameRentals")
                    .HasForeignKey("BoardGameId1");

                b.HasOne("Rental.DataAccess.Entities.Client", "Client")
                    .WithMany("GameRentals")
                    .HasForeignKey("ClientId1");
            });
#pragma warning restore 612, 618
        }
    }
}