// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Rental.DataAccess.Context;

namespace Rental.DataAccess.Migrations
{
    [DbContext(typeof(RentalContext))]
    internal class RentalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("r")
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6");

            modelBuilder.Entity("Rental.DataAccess.Entities.BoardGame", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<DateTime>("CreationTime")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(new DateTime(2019, 8, 11, 6, 7, 13, 727, DateTimeKind.Utc).AddTicks(8863));

                b.Property<string>("Name")
                    .IsRequired();

                b.Property<float>("Price");

                b.HasKey("Id");

                b.ToTable("BoardGames");

                b.HasData(
                    new
                    {
                        Id = new Guid("f776435f-52ba-45d7-8f77-450695189488"),
                        CreationTime = new DateTime(2019, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 182f
                    },
                    new
                    {
                        Id = new Guid("1b7f60df-2e75-488e-b0e8-f3ef8d113903"),
                        CreationTime = new DateTime(2019, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 164f
                    },
                    new
                    {
                        Id = new Guid("47ff77a6-a27d-4387-9880-0f281dd49d4d"),
                        CreationTime = new DateTime(2019, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 222f
                    },
                    new
                    {
                        Id = new Guid("a184ecda-ded7-4b3f-a083-8f8360114d18"),
                        CreationTime = new DateTime(2019, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 198f
                    },
                    new
                    {
                        Id = new Guid("4cd8864d-da8c-447c-b92f-f8523b1a47f2"),
                        CreationTime = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 198f
                    },
                    new
                    {
                        Id = new Guid("341fe361-49cf-4720-85d8-36087bd36e79"),
                        CreationTime = new DateTime(2019, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 106f
                    },
                    new
                    {
                        Id = new Guid("e5ae84a2-605e-431d-bb17-523324192bd9"),
                        CreationTime = new DateTime(2019, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 243f
                    },
                    new
                    {
                        Id = new Guid("bf42a1e6-4d8b-4d2b-8531-e9d394340278"),
                        CreationTime = new DateTime(2019, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 141f
                    },
                    new
                    {
                        Id = new Guid("f381144e-1ad6-4e2a-b0dc-326a6f79b4c7"),
                        CreationTime = new DateTime(2019, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 129f
                    },
                    new
                    {
                        Id = new Guid("6ead2c39-74f9-4603-959d-2501712f6f69"),
                        CreationTime = new DateTime(2019, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 81f
                    },
                    new
                    {
                        Id = new Guid("7300b8ad-2f2c-4005-8384-97883109ba7a"),
                        CreationTime = new DateTime(2019, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 54f
                    },
                    new
                    {
                        Id = new Guid("fc0fcf5f-cb25-4649-b533-60f6eb3f5909"),
                        CreationTime = new DateTime(2019, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 85f
                    },
                    new
                    {
                        Id = new Guid("0d168485-3d1e-44d0-be49-35550ea47814"),
                        CreationTime = new DateTime(2019, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 62f
                    },
                    new
                    {
                        Id = new Guid("7ece71b5-8760-4f5c-bd9e-6e69844c8416"),
                        CreationTime = new DateTime(2019, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 133f
                    },
                    new
                    {
                        Id = new Guid("f3d8fba1-5679-4fb6-8d4d-f0c05ac7a6af"),
                        CreationTime = new DateTime(2019, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 57f
                    },
                    new
                    {
                        Id = new Guid("11efb3b0-fc49-414b-945b-cdcbe0a86da8"),
                        CreationTime = new DateTime(2019, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 154f
                    },
                    new
                    {
                        Id = new Guid("874a2e82-91e2-4801-af16-b22aa9ef9c38"),
                        CreationTime = new DateTime(2019, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 248f
                    },
                    new
                    {
                        Id = new Guid("3821dbfe-3188-4abe-a8f5-38d60cac2228"),
                        CreationTime = new DateTime(2019, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 207f
                    },
                    new
                    {
                        Id = new Guid("8a313dc1-5a02-4e8a-b377-a299768f98b6"),
                        CreationTime = new DateTime(2019, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 230f
                    },
                    new
                    {
                        Id = new Guid("03ad766a-4570-42aa-ae4d-6b73af391527"),
                        CreationTime = new DateTime(2019, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 72f
                    },
                    new
                    {
                        Id = new Guid("36221789-a567-4e05-9cfd-befa1c89f220"),
                        CreationTime = new DateTime(2019, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 141f
                    },
                    new
                    {
                        Id = new Guid("00462b00-90ee-48bc-8af4-c2e6912c765c"),
                        CreationTime = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 165f
                    },
                    new
                    {
                        Id = new Guid("6ee097bc-cef5-4c38-9a41-63d0e2977486"),
                        CreationTime = new DateTime(2019, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 79f
                    },
                    new
                    {
                        Id = new Guid("9e41cfa2-b903-475c-834a-46c5c6c38665"),
                        CreationTime = new DateTime(2019, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 79f
                    },
                    new
                    {
                        Id = new Guid("f74c472b-139e-4bbd-9c7c-aa1c7fb6cee3"),
                        CreationTime = new DateTime(2019, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 177f
                    },
                    new
                    {
                        Id = new Guid("6f9201df-99d6-468f-81fc-be59ee4f9286"),
                        CreationTime = new DateTime(2019, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 62f
                    },
                    new
                    {
                        Id = new Guid("2c80dd98-649f-4ca2-98df-7513481d8d26"),
                        CreationTime = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 111f
                    },
                    new
                    {
                        Id = new Guid("a5f39d3a-b716-4cd2-bd10-00dd3a995b65"),
                        CreationTime = new DateTime(2019, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 248f
                    },
                    new
                    {
                        Id = new Guid("8e07df45-ba33-4526-bd07-458cf282308e"),
                        CreationTime = new DateTime(2019, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 133f
                    },
                    new
                    {
                        Id = new Guid("d9f931f7-31e8-490a-97e7-7bc54b6a9363"),
                        CreationTime = new DateTime(2019, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 148f
                    },
                    new
                    {
                        Id = new Guid("105601c3-3468-4ef7-a393-6cf6668cecbb"),
                        CreationTime = new DateTime(2019, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 145f
                    },
                    new
                    {
                        Id = new Guid("7e0d89d8-ed3e-4772-974b-ca9e0b553e68"),
                        CreationTime = new DateTime(2019, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 147f
                    },
                    new
                    {
                        Id = new Guid("dbd38fbf-0583-4d48-b81e-f3bdcbf60f4c"),
                        CreationTime = new DateTime(2019, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 191f
                    },
                    new
                    {
                        Id = new Guid("1c1cb5b7-362a-4278-9eb8-752c1ed7e202"),
                        CreationTime = new DateTime(2019, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 144f
                    },
                    new
                    {
                        Id = new Guid("f162ad17-7f88-465b-ac3b-dda3a0a34e60"),
                        CreationTime = new DateTime(2019, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 197f
                    },
                    new
                    {
                        Id = new Guid("6ec0213e-f8bc-4b79-9864-372007818bb1"),
                        CreationTime = new DateTime(2019, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 214f
                    },
                    new
                    {
                        Id = new Guid("09622a47-32c8-4225-a73e-61009efb5d03"),
                        CreationTime = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 248f
                    },
                    new
                    {
                        Id = new Guid("bc02e975-11f1-47bd-b82c-7e2d21ebf5e3"),
                        CreationTime = new DateTime(2019, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 129f
                    },
                    new
                    {
                        Id = new Guid("7d54a858-6932-45cb-9b3f-2bd707ddec8e"),
                        CreationTime = new DateTime(2019, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 73f
                    },
                    new
                    {
                        Id = new Guid("d5ebd11b-4165-4f60-ac26-62523ee211ce"),
                        CreationTime = new DateTime(2019, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 193f
                    },
                    new
                    {
                        Id = new Guid("443b9b36-19bc-4027-b160-5ff9dd9e7a39"),
                        CreationTime = new DateTime(2019, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 192f
                    },
                    new
                    {
                        Id = new Guid("b9ba7b67-8923-455a-b022-915bd61a7481"),
                        CreationTime = new DateTime(2019, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 112f
                    },
                    new
                    {
                        Id = new Guid("a4a7b644-6025-4845-9178-bcb807c867fa"),
                        CreationTime = new DateTime(2019, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 72f
                    },
                    new
                    {
                        Id = new Guid("193398ed-8bc8-473c-ade2-a9d6eb19d2be"),
                        CreationTime = new DateTime(2019, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 205f
                    },
                    new
                    {
                        Id = new Guid("e6da9750-8490-453d-9f0e-4591f12a8cf2"),
                        CreationTime = new DateTime(2019, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 158f
                    },
                    new
                    {
                        Id = new Guid("fa21672b-860e-4c24-986b-98549f6ddd87"),
                        CreationTime = new DateTime(2019, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 241f
                    },
                    new
                    {
                        Id = new Guid("6194ed35-1684-4177-8684-af80b1c4aa46"),
                        CreationTime = new DateTime(2019, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 76f
                    },
                    new
                    {
                        Id = new Guid("93b29ce1-56f6-40bd-baed-ac2deef833e4"),
                        CreationTime = new DateTime(2019, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 152f
                    },
                    new
                    {
                        Id = new Guid("adfa8356-bcf4-4d01-81ca-27cc7e9af247"),
                        CreationTime = new DateTime(2019, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 87f
                    },
                    new
                    {
                        Id = new Guid("4e4e18ac-df41-422e-9753-b0d7a6c57042"),
                        CreationTime = new DateTime(2019, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 118f
                    },
                    new
                    {
                        Id = new Guid("dd3d3ccb-d098-4665-acf7-ae2298a4cd18"),
                        CreationTime = new DateTime(2019, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 89f
                    },
                    new
                    {
                        Id = new Guid("fd10b04b-e87a-4f24-9490-459aa3974fd9"),
                        CreationTime = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 98f
                    },
                    new
                    {
                        Id = new Guid("bf2a4d27-a28b-4f5d-a9b8-27d086f10f55"),
                        CreationTime = new DateTime(2019, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 93f
                    },
                    new
                    {
                        Id = new Guid("47c34665-8033-45f5-9017-a9c8d7601ddc"),
                        CreationTime = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 157f
                    },
                    new
                    {
                        Id = new Guid("8feb0198-5669-4cc7-94a4-350f3fec4da7"),
                        CreationTime = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 151f
                    },
                    new
                    {
                        Id = new Guid("d7aac946-9a59-4c00-a6be-1e2b99037b31"),
                        CreationTime = new DateTime(2019, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 66f
                    },
                    new
                    {
                        Id = new Guid("1bbbeb14-21cb-443d-9e5e-b83ac0c7598f"),
                        CreationTime = new DateTime(2019, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 135f
                    },
                    new
                    {
                        Id = new Guid("4f22ce42-ee2a-4d35-9355-0f55d83a29db"),
                        CreationTime = new DateTime(2019, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 193f
                    },
                    new
                    {
                        Id = new Guid("56a72c55-947c-4b17-bada-d2deb7cf7a1c"),
                        CreationTime = new DateTime(2019, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 70f
                    },
                    new
                    {
                        Id = new Guid("109e83cf-8e8b-4bab-bfe2-1d13cf8e7ed6"),
                        CreationTime = new DateTime(2019, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 186f
                    },
                    new
                    {
                        Id = new Guid("b0c8d5ba-3882-4c20-ae2d-7bead2d25d39"),
                        CreationTime = new DateTime(2019, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 245f
                    },
                    new
                    {
                        Id = new Guid("b59fcbc9-c344-48e0-ac72-6bc55065cd12"),
                        CreationTime = new DateTime(2019, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 245f
                    },
                    new
                    {
                        Id = new Guid("a41827d0-7636-49e2-8080-5d00d35b1206"),
                        CreationTime = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 58f
                    },
                    new
                    {
                        Id = new Guid("f40379aa-8f9a-496c-aff5-af3bf60ca884"),
                        CreationTime = new DateTime(2019, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 230f
                    },
                    new
                    {
                        Id = new Guid("134ff0d9-1f2c-494e-a6b6-09c353f0c01f"),
                        CreationTime = new DateTime(2019, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 186f
                    },
                    new
                    {
                        Id = new Guid("73a4be53-0021-4ece-bffd-28db8ec01bf9"),
                        CreationTime = new DateTime(2019, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 156f
                    },
                    new
                    {
                        Id = new Guid("b960d38e-6423-4dfd-8f02-141113b9aa07"),
                        CreationTime = new DateTime(2019, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 144f
                    },
                    new
                    {
                        Id = new Guid("cd43b8db-af67-45dc-8bed-ce1dc3d91782"),
                        CreationTime = new DateTime(2019, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 168f
                    },
                    new
                    {
                        Id = new Guid("fdf3433a-10fa-49b2-bb29-d4878252414f"),
                        CreationTime = new DateTime(2019, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 185f
                    },
                    new
                    {
                        Id = new Guid("91bceaa8-fbf9-4b41-81fd-c25a526dc3a5"),
                        CreationTime = new DateTime(2019, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 92f
                    },
                    new
                    {
                        Id = new Guid("531c2a70-6513-4816-a347-1843e500c5b2"),
                        CreationTime = new DateTime(2019, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 155f
                    },
                    new
                    {
                        Id = new Guid("d9bac877-3e42-47b7-ac09-23338bf7b128"),
                        CreationTime = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 169f
                    },
                    new
                    {
                        Id = new Guid("85e5d3c3-885c-46f2-8c0a-30e47cabb70e"),
                        CreationTime = new DateTime(2019, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 184f
                    },
                    new
                    {
                        Id = new Guid("c175e2ac-e542-4fd9-a01d-74506adc9a6b"),
                        CreationTime = new DateTime(2019, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 86f
                    },
                    new
                    {
                        Id = new Guid("82370fd7-c528-4215-b2ff-5ad3d75cdbe7"),
                        CreationTime = new DateTime(2019, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 130f
                    },
                    new
                    {
                        Id = new Guid("40053388-1ec1-4853-bc62-6115cf13513e"),
                        CreationTime = new DateTime(2019, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 79f
                    },
                    new
                    {
                        Id = new Guid("e4682c9e-b589-401f-97c1-afdffe4fccd2"),
                        CreationTime = new DateTime(2019, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 143f
                    },
                    new
                    {
                        Id = new Guid("d7a14f1c-3376-4052-83fa-891749cc1557"),
                        CreationTime = new DateTime(2019, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 123f
                    },
                    new
                    {
                        Id = new Guid("dbb975cd-e418-4bc5-877a-affb8174b6f4"),
                        CreationTime = new DateTime(2019, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 170f
                    },
                    new
                    {
                        Id = new Guid("7ecbf069-3fea-4e80-b0df-b091ba76585d"),
                        CreationTime = new DateTime(2019, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 186f
                    },
                    new
                    {
                        Id = new Guid("f8523918-5f92-40d5-ac8c-52272274a77b"),
                        CreationTime = new DateTime(2019, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 235f
                    },
                    new
                    {
                        Id = new Guid("b4ff55ab-bb48-44aa-a117-49bf811064be"),
                        CreationTime = new DateTime(2019, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 209f
                    },
                    new
                    {
                        Id = new Guid("306728c7-4615-4383-9bb4-a057f6446587"),
                        CreationTime = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 210f
                    },
                    new
                    {
                        Id = new Guid("64877867-7dd1-4981-b210-1b6273ba6f0a"),
                        CreationTime = new DateTime(2019, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 65f
                    },
                    new
                    {
                        Id = new Guid("960a7013-b318-4098-b398-642e7938c079"),
                        CreationTime = new DateTime(2019, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 109f
                    },
                    new
                    {
                        Id = new Guid("6dc2ed53-ad97-4832-87d6-4007b3451eb3"),
                        CreationTime = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 96f
                    },
                    new
                    {
                        Id = new Guid("e964b20f-5847-452f-8ae0-143b56e9c5f9"),
                        CreationTime = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 104f
                    },
                    new
                    {
                        Id = new Guid("161a053a-bf76-4b32-a574-d0133bf9bb81"),
                        CreationTime = new DateTime(2019, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 84f
                    },
                    new
                    {
                        Id = new Guid("2dbc8ca3-e85f-4ef9-a5f8-b9a521b37353"),
                        CreationTime = new DateTime(2019, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 242f
                    },
                    new
                    {
                        Id = new Guid("64b65da1-3403-40ae-b72f-209998e64d4c"),
                        CreationTime = new DateTime(2019, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 180f
                    },
                    new
                    {
                        Id = new Guid("be3f33fc-87fb-4b11-86f8-cade16ac2881"),
                        CreationTime = new DateTime(2019, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 129f
                    },
                    new
                    {
                        Id = new Guid("ebf0351e-a427-483d-8224-b358095ee755"),
                        CreationTime = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 105f
                    },
                    new
                    {
                        Id = new Guid("021b95cb-e28b-4d2c-ae1d-8c70b25436aa"),
                        CreationTime = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 108f
                    },
                    new
                    {
                        Id = new Guid("4b942334-2bdc-48a9-a049-598e75b2a75a"),
                        CreationTime = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 137f
                    },
                    new
                    {
                        Id = new Guid("65294eea-73fa-4964-82bb-220ed628bf76"),
                        CreationTime = new DateTime(2019, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 198f
                    },
                    new
                    {
                        Id = new Guid("bc0f87f0-549c-431e-b938-f13dcb35a9b9"),
                        CreationTime = new DateTime(2019, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 196f
                    },
                    new
                    {
                        Id = new Guid("3d1bcdc5-36c6-4ebc-a455-9b01a6abfd60"),
                        CreationTime = new DateTime(2019, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 103f
                    },
                    new
                    {
                        Id = new Guid("851d0083-5e1e-447e-99fd-ce6b8c2f0fe3"),
                        CreationTime = new DateTime(2019, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 92f
                    },
                    new
                    {
                        Id = new Guid("e9673244-1bd0-4c0c-9866-b38f509c5856"),
                        CreationTime = new DateTime(2019, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 69f
                    },
                    new
                    {
                        Id = new Guid("8f110aff-b801-44c3-b87a-0d2c4869404e"),
                        CreationTime = new DateTime(2019, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "alias",
                        Price = 52f
                    });
            });

            modelBuilder.Entity("Rental.DataAccess.Entities.Client", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("ContactNumber")
                    .IsRequired();

                b.Property<DateTime>("CreationTime")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(new DateTime(2019, 8, 11, 6, 7, 13, 733, DateTimeKind.Utc).AddTicks(8225));

                b.Property<string>("EmailAddress")
                    .IsRequired();

                b.Property<string>("FirstName")
                    .IsRequired();

                b.Property<string>("LastName")
                    .IsRequired();

                b.HasKey("Id");

                b.ToTable("Clients");

                b.HasData(
                    new
                    {
                        Id = new Guid("24a9ce44-2534-4c54-9d53-b40319a575d9"),
                        ContactNumber = "053-216-2044 x2770",
                        CreationTime = new DateTime(2019, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "bryon@mante.ca",
                        FirstName = "Kellen",
                        LastName = "Abbott"
                    },
                    new
                    {
                        Id = new Guid("f0e7cb03-6acb-4b25-8177-5b460713287e"),
                        ContactNumber = "(720)504-3201 x4687",
                        CreationTime = new DateTime(2019, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "theodore@weimann.info",
                        FirstName = "Adrain",
                        LastName = "Wuckert"
                    },
                    new
                    {
                        Id = new Guid("db5659cf-746a-4fdd-93ed-26612156dcf4"),
                        ContactNumber = "265-677-1006 x6486",
                        CreationTime = new DateTime(2019, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "aileen_breitenberg@rodriguez.ca",
                        FirstName = "Adonis",
                        LastName = "Skiles"
                    },
                    new
                    {
                        Id = new Guid("132066eb-77b8-400e-93e2-66f9b8409345"),
                        ContactNumber = "276.570.6856 x73654",
                        CreationTime = new DateTime(2019, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "cara_block@hane.com",
                        FirstName = "Lizzie",
                        LastName = "Doyle"
                    },
                    new
                    {
                        Id = new Guid("40f06a83-83dd-46a1-b380-2e8e0d0bacf5"),
                        ContactNumber = "600-871-3658",
                        CreationTime = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "garland@mayert.uk",
                        FirstName = "Heaven",
                        LastName = "Waelchi"
                    },
                    new
                    {
                        Id = new Guid("c7202156-faac-4ca8-ad62-3f39b481e9a3"),
                        ContactNumber = "524-474-8485 x75364",
                        CreationTime = new DateTime(2019, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "mallory@okuneva.co.uk",
                        FirstName = "Dewayne",
                        LastName = "Altenwerth"
                    },
                    new
                    {
                        Id = new Guid("92b4cd79-e57a-417b-bcbc-ff3149c7f23f"),
                        ContactNumber = "472.427.1153 x024",
                        CreationTime = new DateTime(2019, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "janet@mckenzie.info",
                        FirstName = "Adaline",
                        LastName = "West"
                    },
                    new
                    {
                        Id = new Guid("d4a2be61-09eb-4dc2-8043-f4cbd97e46fc"),
                        ContactNumber = "623-551-0425 x8266",
                        CreationTime = new DateTime(2019, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "monroe@rau.uk",
                        FirstName = "Doug",
                        LastName = "Barrows"
                    },
                    new
                    {
                        Id = new Guid("d1f5408d-68d0-4b8e-b984-4832f565834f"),
                        ContactNumber = "510.158.1241",
                        CreationTime = new DateTime(2019, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "destin_feil@bernierlittle.info",
                        FirstName = "Judy",
                        LastName = "Buckridge"
                    },
                    new
                    {
                        Id = new Guid("d232b3a2-28aa-47d6-ae77-d07643061450"),
                        ContactNumber = "1-860-462-0722 x111",
                        CreationTime = new DateTime(2019, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "hassie.veum@hackett.info",
                        FirstName = "Pasquale",
                        LastName = "Muller"
                    },
                    new
                    {
                        Id = new Guid("ebd89e66-5613-4e72-b63f-8fe177ee873d"),
                        ContactNumber = "751.315.6456 x4858",
                        CreationTime = new DateTime(2019, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "camylle.doyle@howe.us",
                        FirstName = "Kyra",
                        LastName = "D'Amore"
                    },
                    new
                    {
                        Id = new Guid("bf613030-0739-425b-b583-0b5c12426a11"),
                        ContactNumber = "841-711-8676 x7316",
                        CreationTime = new DateTime(2019, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "lowell@gerholdwisozk.co.uk",
                        FirstName = "Boris",
                        LastName = "Ankunding"
                    },
                    new
                    {
                        Id = new Guid("7d54f999-a097-4d0b-8ff6-134d646d07f6"),
                        ContactNumber = "(225)675-1203 x4622",
                        CreationTime = new DateTime(2019, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "lavern.bergnaum@bartoletti.co.uk",
                        FirstName = "Elisha",
                        LastName = "Bartoletti"
                    },
                    new
                    {
                        Id = new Guid("d5eed847-8bd7-4c88-af34-6e0f7491f055"),
                        ContactNumber = "1-410-183-7785 x44106",
                        CreationTime = new DateTime(2019, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "quentin@mante.com",
                        FirstName = "Ashleigh",
                        LastName = "Eichmann"
                    },
                    new
                    {
                        Id = new Guid("e36a4b3c-42fc-46e4-bbb6-1ca40fefd3a5"),
                        ContactNumber = "(603)868-1447 x1828",
                        CreationTime = new DateTime(2019, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "cristian@kilback.co.uk",
                        FirstName = "Freddy",
                        LastName = "Prosacco"
                    },
                    new
                    {
                        Id = new Guid("42db85a7-0b50-45b3-8bcb-160a357d9b7c"),
                        ContactNumber = "254.841.6143 x4887",
                        CreationTime = new DateTime(2019, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "zoila@wizawolf.us",
                        FirstName = "Robb",
                        LastName = "Watsica"
                    },
                    new
                    {
                        Id = new Guid("e6c1252b-d4a2-4f9e-a29d-0f752c1a5140"),
                        ContactNumber = "(853)160-4570",
                        CreationTime = new DateTime(2019, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "marco.kozey@abshire.co.uk",
                        FirstName = "Tierra",
                        LastName = "Reinger"
                    },
                    new
                    {
                        Id = new Guid("21d586b7-3d4b-41b0-ae21-ef7af98c19f0"),
                        ContactNumber = "342.832.7175 x75453",
                        CreationTime = new DateTime(2019, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "amina@bernier.info",
                        FirstName = "Aliza",
                        LastName = "Kuvalis"
                    },
                    new
                    {
                        Id = new Guid("7e07a52d-1b87-405e-bbb9-7fc33664761c"),
                        ContactNumber = "184-186-2711",
                        CreationTime = new DateTime(2019, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "bessie@douglas.biz",
                        FirstName = "Lolita",
                        LastName = "Spencer"
                    },
                    new
                    {
                        Id = new Guid("310a1e8a-63c8-4faf-97e1-10a754eb3bb1"),
                        ContactNumber = "370.678.7108 x41760",
                        CreationTime = new DateTime(2019, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "ines_murphy@considine.name",
                        FirstName = "Maverick",
                        LastName = "Kemmer"
                    },
                    new
                    {
                        Id = new Guid("b2bd44b1-3e65-4266-a146-d6546c388711"),
                        ContactNumber = "1-117-522-3533",
                        CreationTime = new DateTime(2019, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "darrin@gibsoncassin.ca",
                        FirstName = "Geo",
                        LastName = "Heidenreich"
                    },
                    new
                    {
                        Id = new Guid("8a6bdf05-cc7d-4e58-94f6-eef1d5f59743"),
                        ContactNumber = "(863)838-8027 x0763",
                        CreationTime = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "marlon_hermiston@nikolausfranecki.info",
                        FirstName = "Christopher",
                        LastName = "Von"
                    },
                    new
                    {
                        Id = new Guid("13d5f28d-345e-470b-b5b2-7886f9e5d523"),
                        ContactNumber = "1-511-305-2063 x3713",
                        CreationTime = new DateTime(2019, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "gage.blanda@hettinger.name",
                        FirstName = "Carissa",
                        LastName = "Gorczany"
                    },
                    new
                    {
                        Id = new Guid("83f54ed1-f58c-4eb4-ab39-e8cbd01f3cae"),
                        ContactNumber = "172-414-1166 x762",
                        CreationTime = new DateTime(2019, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "quinn@abbott.name",
                        FirstName = "Sabina",
                        LastName = "Mayer"
                    },
                    new
                    {
                        Id = new Guid("fbd4923b-1c62-4f9d-9e30-73c776ba2f43"),
                        ContactNumber = "206-382-2227 x5436",
                        CreationTime = new DateTime(2019, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "darby@mosciski.co.uk",
                        FirstName = "Jennings",
                        LastName = "Waters"
                    },
                    new
                    {
                        Id = new Guid("239622b3-9641-4a66-97cb-628395f926b8"),
                        ContactNumber = "555-384-6811 x03312",
                        CreationTime = new DateTime(2019, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "kari.lang@murray.co.uk",
                        FirstName = "Keshaun",
                        LastName = "Lang"
                    },
                    new
                    {
                        Id = new Guid("55d55b7f-f9eb-4536-95e3-e28abf953827"),
                        ContactNumber = "242-564-8635 x736",
                        CreationTime = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "marion@gibson.info",
                        FirstName = "Noemie",
                        LastName = "Reichert"
                    },
                    new
                    {
                        Id = new Guid("d335500d-be89-47b6-9439-ab9908a030fe"),
                        ContactNumber = "015.051.7146",
                        CreationTime = new DateTime(2019, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "belle@kohlerweissnat.ca",
                        FirstName = "Raymundo",
                        LastName = "Rohan"
                    },
                    new
                    {
                        Id = new Guid("8a196d12-d7b0-484b-bf3a-3cda261b6f0e"),
                        ContactNumber = "1-383-606-7831 x388",
                        CreationTime = new DateTime(2019, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "tanner.cronin@nitzsche.biz",
                        FirstName = "Elroy",
                        LastName = "Torphy"
                    },
                    new
                    {
                        Id = new Guid("a15dd62e-e2d4-4e25-b762-b73fc2afbeb5"),
                        ContactNumber = "(115)613-6382",
                        CreationTime = new DateTime(2019, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jay@hickle.info",
                        FirstName = "Sammy",
                        LastName = "Daugherty"
                    },
                    new
                    {
                        Id = new Guid("8f8a55a4-3091-4a1c-89a7-2b90463d7840"),
                        ContactNumber = "(162)340-7458",
                        CreationTime = new DateTime(2019, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "karson_grady@tremblaybode.co.uk",
                        FirstName = "Delaney",
                        LastName = "Kirlin"
                    },
                    new
                    {
                        Id = new Guid("6ecb66fc-f520-4d0f-9e3a-34b50c1f2181"),
                        ContactNumber = "885.235.7421",
                        CreationTime = new DateTime(2019, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "harold@spinka.info",
                        FirstName = "Myra",
                        LastName = "Brakus"
                    },
                    new
                    {
                        Id = new Guid("61b9500e-ac1d-4ffd-bfe5-796ed8ea9df9"),
                        ContactNumber = "1-426-847-6466",
                        CreationTime = new DateTime(2019, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "murl@hellerosinski.us",
                        FirstName = "Daniella",
                        LastName = "Funk"
                    },
                    new
                    {
                        Id = new Guid("3a776a95-0896-4815-95be-e262999c8f75"),
                        ContactNumber = "1-048-037-2153",
                        CreationTime = new DateTime(2019, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "anika@schroeder.com",
                        FirstName = "Nedra",
                        LastName = "Reichel"
                    },
                    new
                    {
                        Id = new Guid("925815e3-0da9-422a-b7b2-2ed365132d70"),
                        ContactNumber = "(461)070-3804",
                        CreationTime = new DateTime(2019, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "luciano.cartwright@okeefe.com",
                        FirstName = "Bobby",
                        LastName = "Altenwerth"
                    },
                    new
                    {
                        Id = new Guid("fc59a3e9-668b-4a9c-bb29-8389c46d441b"),
                        ContactNumber = "510-453-8874",
                        CreationTime = new DateTime(2019, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "myron@mannhintz.us",
                        FirstName = "Hyman",
                        LastName = "Corkery"
                    },
                    new
                    {
                        Id = new Guid("0d2730c5-445d-43fd-9e44-b0e3a6767b30"),
                        ContactNumber = "430-185-8658",
                        CreationTime = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "valentina_stracke@thompson.ca",
                        FirstName = "Tressa",
                        LastName = "Gibson"
                    },
                    new
                    {
                        Id = new Guid("96776636-6760-4579-84fb-8b1b619abbd2"),
                        ContactNumber = "(028)384-4735 x816",
                        CreationTime = new DateTime(2019, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "lacy.buckridge@okon.name",
                        FirstName = "Celestine",
                        LastName = "Raynor"
                    },
                    new
                    {
                        Id = new Guid("68026d92-8099-40b0-ae56-b30dc85c143b"),
                        ContactNumber = "1-776-713-0482 x715",
                        CreationTime = new DateTime(2019, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jeramie.rowe@herzogauer.uk",
                        FirstName = "Rasheed",
                        LastName = "Mayer"
                    },
                    new
                    {
                        Id = new Guid("9efac78b-40e9-46b9-842f-7d6e4c259912"),
                        ContactNumber = "(405)401-1437",
                        CreationTime = new DateTime(2019, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "marina@williamson.info",
                        FirstName = "Carrie",
                        LastName = "Barton"
                    },
                    new
                    {
                        Id = new Guid("60a1d5e7-0552-447a-a9a0-413490459d6b"),
                        ContactNumber = "1-774-114-5245 x066",
                        CreationTime = new DateTime(2019, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "hazel@roob.uk",
                        FirstName = "Margret",
                        LastName = "Reilly"
                    },
                    new
                    {
                        Id = new Guid("7afb4d78-d131-4046-b962-1f16cf354f03"),
                        ContactNumber = "766.727.3117",
                        CreationTime = new DateTime(2019, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jerrod@nitzschekozey.uk",
                        FirstName = "Rita",
                        LastName = "Cummerata"
                    },
                    new
                    {
                        Id = new Guid("4a5e5e76-5999-4e82-be10-4cd9def2cd0c"),
                        ContactNumber = "787.728.4404 x228",
                        CreationTime = new DateTime(2019, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "hayley@schinner.com",
                        FirstName = "Federico",
                        LastName = "Mohr"
                    },
                    new
                    {
                        Id = new Guid("a421269a-8757-41dd-a429-3f8d316748c3"),
                        ContactNumber = "1-312-276-6327",
                        CreationTime = new DateTime(2019, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "fay@bodeweimann.us",
                        FirstName = "Norene",
                        LastName = "Swaniawski"
                    },
                    new
                    {
                        Id = new Guid("7c972ba9-0af8-4171-8daa-49c6531f0000"),
                        ContactNumber = "(358)541-0667",
                        CreationTime = new DateTime(2019, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jackson_welch@jaskolskimedhurst.co.uk",
                        FirstName = "Selina",
                        LastName = "Smitham"
                    },
                    new
                    {
                        Id = new Guid("e537be85-9d8a-4452-ab0a-d0165d4354c8"),
                        ContactNumber = "210.350.0771 x4243",
                        CreationTime = new DateTime(2019, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jamal_renner@sawayn.name",
                        FirstName = "Marques",
                        LastName = "Medhurst"
                    },
                    new
                    {
                        Id = new Guid("17e29685-c7b1-4c9e-98fe-8bfca505f475"),
                        ContactNumber = "336.632.1240",
                        CreationTime = new DateTime(2019, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "shane.ullrich@beahan.info",
                        FirstName = "Jacques",
                        LastName = "Farrell"
                    },
                    new
                    {
                        Id = new Guid("8dac56da-1365-4b50-8d81-98d2113df192"),
                        ContactNumber = "1-248-882-5762",
                        CreationTime = new DateTime(2019, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "rachel_dooley@heathcotedonnelly.ca",
                        FirstName = "Maryam",
                        LastName = "Larson"
                    },
                    new
                    {
                        Id = new Guid("b56a1418-d5aa-43ca-993d-030f266ac910"),
                        ContactNumber = "(031)537-0621",
                        CreationTime = new DateTime(2019, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "melody.champlin@ratke.co.uk",
                        FirstName = "Sandrine",
                        LastName = "Graham"
                    },
                    new
                    {
                        Id = new Guid("e72eda1b-127c-4be5-93ad-b7dd3b8d0653"),
                        ContactNumber = "670-164-6527 x20217",
                        CreationTime = new DateTime(2019, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "kasandra@lindgrenbins.uk",
                        FirstName = "Lisette",
                        LastName = "Keeling"
                    },
                    new
                    {
                        Id = new Guid("9bb9a8d0-9559-403c-99a3-6dcc4f01590b"),
                        ContactNumber = "(606)541-7551",
                        CreationTime = new DateTime(2019, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "everett_emmerich@lemke.biz",
                        FirstName = "Carmelo",
                        LastName = "Von"
                    },
                    new
                    {
                        Id = new Guid("13c4dd80-59e4-4511-b2cb-48a0fd2027e8"),
                        ContactNumber = "(176)837-4033 x588",
                        CreationTime = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "loraine@bins.name",
                        FirstName = "Ruthe",
                        LastName = "Welch"
                    },
                    new
                    {
                        Id = new Guid("5445933e-85e4-4ea2-9b2b-d95cf83c063c"),
                        ContactNumber = "1-547-230-0728",
                        CreationTime = new DateTime(2019, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "kristy.wisozk@boyer.ca",
                        FirstName = "Kiley",
                        LastName = "Kemmer"
                    },
                    new
                    {
                        Id = new Guid("62c3abc4-a3b5-4827-bada-176d00618701"),
                        ContactNumber = "346.468.4688 x66134",
                        CreationTime = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "casandra.hand@haagwatsica.us",
                        FirstName = "Dorian",
                        LastName = "Schmitt"
                    },
                    new
                    {
                        Id = new Guid("6c63fc1d-f9a3-4b23-8d84-8e21b540afa2"),
                        ContactNumber = "307-581-2502 x57202",
                        CreationTime = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "zetta_stanton@schowalterhammes.ca",
                        FirstName = "Samara",
                        LastName = "Hoppe"
                    },
                    new
                    {
                        Id = new Guid("eab11ea0-6b92-43c6-9a7d-1d3fc4a54ac5"),
                        ContactNumber = "(815)418-0853 x728",
                        CreationTime = new DateTime(2019, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "hector_hilpert@weissnat.info",
                        FirstName = "Preston",
                        LastName = "Cronin"
                    },
                    new
                    {
                        Id = new Guid("93ce18e1-3cc9-4acf-8504-716c7391ccb9"),
                        ContactNumber = "(850)780-4044 x1084",
                        CreationTime = new DateTime(2019, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "madison@greenfelder.info",
                        FirstName = "Dejon",
                        LastName = "Gusikowski"
                    },
                    new
                    {
                        Id = new Guid("7249191d-78f4-4f40-8fc8-fea9174d392d"),
                        ContactNumber = "(028)377-6688",
                        CreationTime = new DateTime(2019, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "kaylee_fisher@moen.info",
                        FirstName = "Manley",
                        LastName = "Schuster"
                    },
                    new
                    {
                        Id = new Guid("af48b2e5-743e-43ec-8d1e-fb8f35812f58"),
                        ContactNumber = "1-570-244-7372",
                        CreationTime = new DateTime(2019, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "napoleon_reynolds@cole.ca",
                        FirstName = "Gregorio",
                        LastName = "Herzog"
                    },
                    new
                    {
                        Id = new Guid("6ef135d7-f058-48da-9dfe-d76f34525cad"),
                        ContactNumber = "885-643-7817",
                        CreationTime = new DateTime(2019, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "taya@pacocha.ca",
                        FirstName = "Richie",
                        LastName = "Labadie"
                    },
                    new
                    {
                        Id = new Guid("4430c8d1-dd2c-4d4e-9266-bf5976bbf9f2"),
                        ContactNumber = "1-412-614-2474 x25705",
                        CreationTime = new DateTime(2019, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jordy_wilkinson@weimann.biz",
                        FirstName = "George",
                        LastName = "Collier"
                    },
                    new
                    {
                        Id = new Guid("9d745909-664a-4a2f-88ee-922d59a18236"),
                        ContactNumber = "808-752-6567 x67500",
                        CreationTime = new DateTime(2019, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "chloe@mcculloughstark.co.uk",
                        FirstName = "Isobel",
                        LastName = "Hoppe"
                    },
                    new
                    {
                        Id = new Guid("bf645981-14e9-4c51-98f8-73bf736075f9"),
                        ContactNumber = "(603)880-3732",
                        CreationTime = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "catalina_watsica@anderson.uk",
                        FirstName = "Marta",
                        LastName = "Bechtelar"
                    },
                    new
                    {
                        Id = new Guid("1510533e-6e1e-40a6-98cf-9bce52e5842b"),
                        ContactNumber = "(780)520-7462 x0605",
                        CreationTime = new DateTime(2019, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "nya_okuneva@smithklein.us",
                        FirstName = "Pearline",
                        LastName = "Daugherty"
                    },
                    new
                    {
                        Id = new Guid("f2efa964-4c8b-40a2-b1b3-d0583c6f09d2"),
                        ContactNumber = "1-275-872-2001 x4737",
                        CreationTime = new DateTime(2019, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "wilfred@lowe.name",
                        FirstName = "Jonathon",
                        LastName = "Weissnat"
                    },
                    new
                    {
                        Id = new Guid("c921e6d3-6389-4904-9f92-cb68331061a0"),
                        ContactNumber = "056-332-5318",
                        CreationTime = new DateTime(2019, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "elisabeth.luettgen@wisoky.co.uk",
                        FirstName = "Rickey",
                        LastName = "Gislason"
                    },
                    new
                    {
                        Id = new Guid("5ebdbfe4-39b5-4ebf-824f-ed73bef73722"),
                        ContactNumber = "1-270-756-2773 x43715",
                        CreationTime = new DateTime(2019, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "myra_miller@parker.info",
                        FirstName = "Gust",
                        LastName = "Goyette"
                    },
                    new
                    {
                        Id = new Guid("303f2e9f-7f19-411b-b013-93479615743a"),
                        ContactNumber = "(523)277-8137",
                        CreationTime = new DateTime(2019, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jaylan@schultzconsidine.us",
                        FirstName = "Alice",
                        LastName = "Pfannerstill"
                    },
                    new
                    {
                        Id = new Guid("384da756-3670-4f70-a68c-8816afc3cc15"),
                        ContactNumber = "867.377.1712 x7001",
                        CreationTime = new DateTime(2019, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "cecilia@hills.biz",
                        FirstName = "Ana",
                        LastName = "McClure"
                    },
                    new
                    {
                        Id = new Guid("122e3b29-6775-48e0-83a9-19e4bac28d8d"),
                        ContactNumber = "642.178.2322 x6578",
                        CreationTime = new DateTime(2019, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "garth_becker@waters.us",
                        FirstName = "Hilton",
                        LastName = "Pfeffer"
                    },
                    new
                    {
                        Id = new Guid("fae389ba-9dff-496e-963b-e3caec311b7a"),
                        ContactNumber = "104-814-0062 x5001",
                        CreationTime = new DateTime(2019, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "hipolito_russel@runolfsdottirhoppe.co.uk",
                        FirstName = "Elton",
                        LastName = "Gleason"
                    },
                    new
                    {
                        Id = new Guid("ffac5957-2e3c-4e80-915f-4ae4395987e5"),
                        ContactNumber = "(556)272-8817",
                        CreationTime = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "terrill@collins.ca",
                        FirstName = "Rocky",
                        LastName = "DuBuque"
                    },
                    new
                    {
                        Id = new Guid("06512c71-41d1-4a11-aff3-547ca5fbedd0"),
                        ContactNumber = "650-581-0484",
                        CreationTime = new DateTime(2019, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "carley@gleason.ca",
                        FirstName = "Oceane",
                        LastName = "Effertz"
                    },
                    new
                    {
                        Id = new Guid("a7e40221-f703-4d06-bb81-6c27afdce27b"),
                        ContactNumber = "706.073.5445 x1157",
                        CreationTime = new DateTime(2019, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jadyn.marquardt@rosenbaum.info",
                        FirstName = "Roselyn",
                        LastName = "Frami"
                    },
                    new
                    {
                        Id = new Guid("307fd51a-e9f9-4614-9250-30402bb092d6"),
                        ContactNumber = "751-535-3383 x104",
                        CreationTime = new DateTime(2019, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "dallas@moenlarson.name",
                        FirstName = "Modesto",
                        LastName = "Beatty"
                    },
                    new
                    {
                        Id = new Guid("7f4bb0d1-4287-4e11-9744-32e336049a76"),
                        ContactNumber = "247-387-4603 x5586",
                        CreationTime = new DateTime(2019, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "sage@altenwerth.info",
                        FirstName = "Moses",
                        LastName = "Halvorson"
                    },
                    new
                    {
                        Id = new Guid("5f832539-20f2-492d-b7d8-732d53dc596a"),
                        ContactNumber = "1-383-734-2721 x225",
                        CreationTime = new DateTime(2019, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "vesta_mohr@haley.uk",
                        FirstName = "Lorenz",
                        LastName = "Koelpin"
                    },
                    new
                    {
                        Id = new Guid("1f2e5aa0-04b7-4fd7-b346-0936f911f8bd"),
                        ContactNumber = "(863)784-0703 x348",
                        CreationTime = new DateTime(2019, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "carroll@lebsack.info",
                        FirstName = "Scottie",
                        LastName = "Crona"
                    },
                    new
                    {
                        Id = new Guid("6bc4008a-616a-41d7-86d6-fb8f4b002226"),
                        ContactNumber = "121-821-6812",
                        CreationTime = new DateTime(2019, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "jermey@volkman.biz",
                        FirstName = "Ivah",
                        LastName = "Streich"
                    },
                    new
                    {
                        Id = new Guid("98947815-61fa-4a17-a267-b8c9c17414e9"),
                        ContactNumber = "341-561-5203 x3006",
                        CreationTime = new DateTime(2019, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "kaylee@kovacek.com",
                        FirstName = "Darrick",
                        LastName = "Kertzmann"
                    },
                    new
                    {
                        Id = new Guid("5b58b32e-f48c-40af-82c7-29c2bf3ba024"),
                        ContactNumber = "(553)758-7402",
                        CreationTime = new DateTime(2019, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "maida.lakin@cummings.ca",
                        FirstName = "Hoyt",
                        LastName = "Hamill"
                    },
                    new
                    {
                        Id = new Guid("97694fd3-b46b-4958-8447-67bcf7e1f419"),
                        ContactNumber = "(340)634-1463 x81801",
                        CreationTime = new DateTime(2019, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "mittie_cole@thompsonabernathy.info",
                        FirstName = "Samanta",
                        LastName = "Ritchie"
                    },
                    new
                    {
                        Id = new Guid("25b1af46-4282-4da8-a48a-e67bd3b959d0"),
                        ContactNumber = "224.165.5321",
                        CreationTime = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "bernardo@kohler.name",
                        FirstName = "Brook",
                        LastName = "Larson"
                    },
                    new
                    {
                        Id = new Guid("abcc8367-1ed5-45fb-a690-858dfd67c97e"),
                        ContactNumber = "424.037.7618 x368",
                        CreationTime = new DateTime(2019, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "abner@wiegand.ca",
                        FirstName = "Elda",
                        LastName = "Turner"
                    },
                    new
                    {
                        Id = new Guid("74ccc071-6dbd-445d-b83a-d3ed50d76012"),
                        ContactNumber = "460-354-5786 x7401",
                        CreationTime = new DateTime(2019, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "boris.greenholt@smitham.name",
                        FirstName = "Lourdes",
                        LastName = "Jones"
                    },
                    new
                    {
                        Id = new Guid("e231eb38-0186-48ea-b569-33995acadfb2"),
                        ContactNumber = "(126)862-1766 x00230",
                        CreationTime = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "antonietta@spinkaheathcote.com",
                        FirstName = "Holden",
                        LastName = "Koss"
                    },
                    new
                    {
                        Id = new Guid("cb88d6c8-1944-4ba6-89ab-d7c81c6fb5e3"),
                        ContactNumber = "827-520-7586 x23188",
                        CreationTime = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "gianni.hermann@bailey.co.uk",
                        FirstName = "Shad",
                        LastName = "Heller"
                    },
                    new
                    {
                        Id = new Guid("206f9163-486e-46a8-8d19-b41057c27152"),
                        ContactNumber = "325.162.8803 x45568",
                        CreationTime = new DateTime(2019, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "beverly_bergstrom@feest.com",
                        FirstName = "Janice",
                        LastName = "Russel"
                    },
                    new
                    {
                        Id = new Guid("486bf75f-5719-4b67-9fe6-9a5d5bed5890"),
                        ContactNumber = "1-277-227-2648 x780",
                        CreationTime = new DateTime(2019, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "davion@lowe.biz",
                        FirstName = "Verner",
                        LastName = "Ullrich"
                    },
                    new
                    {
                        Id = new Guid("472f9a86-50a0-43cd-96df-5e72cedf31ed"),
                        ContactNumber = "1-843-062-5317 x660",
                        CreationTime = new DateTime(2019, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "cyril@rosenbaum.name",
                        FirstName = "Mable",
                        LastName = "DuBuque"
                    },
                    new
                    {
                        Id = new Guid("2f327e5c-00b2-4c1e-8bb8-107b575ec94c"),
                        ContactNumber = "1-402-810-1127",
                        CreationTime = new DateTime(2019, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "eliseo@parker.ca",
                        FirstName = "Fred",
                        LastName = "Lesch"
                    },
                    new
                    {
                        Id = new Guid("57d1b103-5274-4d8b-879b-c0889875ff4d"),
                        ContactNumber = "512-616-2803 x5785",
                        CreationTime = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "frankie_runolfsson@mante.co.uk",
                        FirstName = "Jan",
                        LastName = "Thiel"
                    },
                    new
                    {
                        Id = new Guid("5109c947-4203-4ddd-abbb-9c50226effe3"),
                        ContactNumber = "724-207-4486 x3747",
                        CreationTime = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "nicole@bosco.com",
                        FirstName = "Liam",
                        LastName = "Treutel"
                    },
                    new
                    {
                        Id = new Guid("84abdaca-da09-4aed-abfe-4eed66826102"),
                        ContactNumber = "(647)632-3543",
                        CreationTime = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "francesca@schmelerpollich.co.uk",
                        FirstName = "Cody",
                        LastName = "Hartmann"
                    },
                    new
                    {
                        Id = new Guid("e668ac7f-b51d-4ad0-b5e6-c3ba49debcc4"),
                        ContactNumber = "085.538.5708",
                        CreationTime = new DateTime(2019, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "marilyne.kirlin@smitham.com",
                        FirstName = "Kurt",
                        LastName = "Cassin"
                    },
                    new
                    {
                        Id = new Guid("fb0b2ba7-b09c-4980-9d76-91ce53bc544b"),
                        ContactNumber = "418.334.8840",
                        CreationTime = new DateTime(2019, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "audie@gerhold.name",
                        FirstName = "Andy",
                        LastName = "Buckridge"
                    },
                    new
                    {
                        Id = new Guid("97724559-aff2-4bd5-90ef-09fd62b7597b"),
                        ContactNumber = "435.666.8488 x7401",
                        CreationTime = new DateTime(2019, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "raegan_corwin@keeling.info",
                        FirstName = "Jedidiah",
                        LastName = "Schultz"
                    },
                    new
                    {
                        Id = new Guid("54548b85-e4f0-4088-a31d-9916d1c1a7db"),
                        ContactNumber = "1-551-666-5226 x041",
                        CreationTime = new DateTime(2019, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "madie_larkin@larkin.co.uk",
                        FirstName = "Josie",
                        LastName = "Stroman"
                    },
                    new
                    {
                        Id = new Guid("1ac8af88-3fdd-4d82-8139-1a479d98dee5"),
                        ContactNumber = "1-473-315-8720 x066",
                        CreationTime = new DateTime(2019, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "darrion@gottlieb.ca",
                        FirstName = "Makenzie",
                        LastName = "Murazik"
                    },
                    new
                    {
                        Id = new Guid("3376a073-81e8-4a93-a997-09f84cf1ec63"),
                        ContactNumber = "337-170-6648 x511",
                        CreationTime = new DateTime(2019, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        EmailAddress = "daniella_dicki@carter.name",
                        FirstName = "Lenna",
                        LastName = "Herzog"
                    });
            });

            modelBuilder.Entity("Rental.DataAccess.Entities.GameRental", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<Guid>("BoardGameId");

                b.Property<float>("ChargedDeposit");

                b.Property<Guid>("ClientId");

                b.Property<DateTime>("CreationTime")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(new DateTime(2019, 8, 11, 6, 7, 13, 733, DateTimeKind.Utc).AddTicks(2484));

                b.Property<DateTime?>("FinishTime");

                b.Property<float>("PaidMoney");

                b.Property<int>("Status");

                b.HasKey("Id");

                b.HasIndex("BoardGameId");

                b.HasIndex("ClientId");

                b.ToTable("GameRentals");
            });

            modelBuilder.Entity("Rental.DataAccess.Entities.GameRental", b =>
            {
                b.HasOne("Rental.DataAccess.Entities.BoardGame", "BoardGame")
                    .WithMany("GameRentals")
                    .HasForeignKey("BoardGameId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Rental.DataAccess.Entities.Client", "Client")
                    .WithMany("GameRentals")
                    .HasForeignKey("ClientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}