version: '3.4'

services:
  clients.api:
    image: ${DOCKER_REGISTRY-}clientsapi
    build:
      context: .
      dockerfile: Clients.Api/Dockerfile

  games.api:
    image: ${DOCKER_REGISTRY-}gamesapi
    build:
      context: .
      dockerfile: Games.Api/Dockerfile


  gateway.api.ocelot:
    image: ${DOCKER_REGISTRY-}gatewayapiocelot
    build:
      context: .
      dockerfile: Gateway.Api.Ocelot/Dockerfile

