version: '3.4'

services:
  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      ports:
        - 27017:27017

  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
      depends_on:
        - mongo

  sqlserver.linux:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"

  clients.api:
    image: ${DOCKER_REGISTRY-}clientsapi
    build:
      context: .
      dockerfile: Services/Clients.Api/Dockerfile
    depends_on:
            - sqlserver.linux

  games.api:
    image: ${DOCKER_REGISTRY-}gamesapi
    build:
      context: .
      dockerfile: Services/Games.Api/Dockerfile
    depends_on:
            - sqlserver.linux

  gateway.api.ocelot:
    image: ${DOCKER_REGISTRY-}gatewayapiocelot
    build:
      context: .
      dockerfile: Gateway/Gateway.Api.Ocelot/Dockerfile
  rentals.api:
    image: ${DOCKER_REGISTRY-}rentalsapi
    build:
      context: .
      dockerfile: Services/Rentals.Api/Dockerfile

