version: '3.4'

services:
  clients.db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"

  clients.api:
    image: ${DOCKER_REGISTRY-}clientsapi
    build:
      context: .
      dockerfile: Clients.Api/Dockerfile
    depends_on:
            - clients.db

  games.api:
    image: ${DOCKER_REGISTRY-}gamesapi
    build:
      context: .
      dockerfile: Games.Api/Dockerfile


  gateway.api.ocelot:
    image: ${DOCKER_REGISTRY-}gatewayapiocelot
    build:
      context: .
      dockerfile: Gateway.Api.Ocelot/Dockerfile

